using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading;

namespace ISCopyFiles
{
    class Program
    {
        static long CopySingleFile( string BaseFolder, FileInfo File )
        {
            Console.Write( "Copying: " + File.Name );

            DirectoryInfo DestFolder = new DirectoryInfo( BaseFolder );
            if( !DestFolder.Exists )
            {
                DestFolder.Create();
            }
            
            string FullName = BaseFolder + "/" + File.Name;
            FileInfo DestFileInfo = new FileInfo( FullName );
            if( DestFileInfo.Exists )
            {
                DestFileInfo.IsReadOnly = false;
                DestFileInfo.Delete();
            }

            File.CopyTo( FullName );
            Console.WriteLine( " ... done!" );

            System.Threading.Thread.Sleep( 50 );

            return ( File.Length );
        }

        static void Main( string[] Args )
        {
            if( Args.Length < 2 )
            {
                Console.WriteLine( "Copies the cab files generated by InstallShield to a common destination folder." );
                Console.WriteLine( "Usage: ISCopyFiles <Source> <Destination>" );
                return;
            }

            int FilesCopied = 0;
            long BytesCopied = 0;

            DirectoryInfo Directory = new DirectoryInfo( Args[0] );
            if( Directory.Exists )
            {
                FileInfo[] Files = Directory.GetFiles();
                foreach( FileInfo File in Files )
                {
                    BytesCopied += CopySingleFile( Args[1], File );
                    FilesCopied++;
                }

                // Copy any localised resources
                DirectoryInfo[] Dirs = Directory.GetDirectories();
                foreach( DirectoryInfo Dir in Dirs )
                {
                    // Check for loc subfolder
                    if( Dir.Name.Length == 2 )
                    {
                        FileInfo[] LocFiles = Dir.GetFiles( "*.dll" );
                        foreach( FileInfo File in LocFiles )
                        {
                            BytesCopied += CopySingleFile( Args[1] + "/" + Dir.Name, File );
                            FilesCopied++;
                        }
                    }
                }

                BytesCopied /= 1024 * 1024;
                Console.WriteLine( "ISCopyFiles success: " + FilesCopied.ToString() + " files copied totalling " + BytesCopied.ToString() + " MB." );
            }
            else
            {
                Console.WriteLine( "Error, ISCopyFiles: Source folder does not exist." );
            }
        }
    }
}
