[Configuration]
BasedOn=..\Engine\Config\BaseEditor.ini

[ModPackages]
ModPackagesInPath=..\BmGame\Src
ModOutputDir=..\BmGame\Unpublished\CookedPC\Script

[Cooker.FaceFXOptions]
bGeneratePersistentMapAnimSet=false

[Editor.ContentTagIndex]
+DefaultTags=(AssetTypeName="Engine.StaticMesh",Tags=(Arch,Ash,Brick,Blood,Building,Cave,Chair,Character,COG,Column,Concrete,Corner,Couch,Cover,Crate,Decoration,Destroyed,Dome,Door,Electronic,Exterior,Facade,Fire,Flare,Floor,Foliage,Fracture,Furniture,Glass,Gore,Hail,HeroPiece,Ice,Ink,Interior,Ladder,Lever,Light,Liquid,Locust,Mechanical,Metal,Mountain,Optimization_Done,Optimization_ToDo,Optimization_NotNeeded,Organic,Physics,Pipe,Railing,Riftworm,Road,Rock,Roof,Rubble,Sidewalk,Sign,Sky,Snow,Stairs,Stone,Stranded,Table,Trash,Tree,Trim,Tunnel,Urban,Vehicle,Volumetric,Wall,Weapon,Wheel,Window,Wood)))
+DefaultTags=(AssetTypeName="Engine.ParticleSystem",Tags=(Ash,Beam,Blood,Camera,Dirt,Dust,Electricity,Explosion,Fire,Fog,Impact,Imulsion,Ink,Liquid,Metal,Mud,MuzzleFlash,Optimization_Done,Optimization_ToDo,Optimization_NotNeeded,Riftworm,Shell,Smoke,Snow,Spark,Stone,Water,Weapon,Wood))
+DefaultTags=(AssetTypeName="Engine.Material",Tags=(Ash,Asphalt,Blood,Brick,Ceiling,Character,COG,Column,Concrete,Damaged,Decal,Dirt,Distortion,Door,Dust,Electricity,Explosion,Exterior,Fire,Flare,Floor,Fog,Foliage,Gases,Glass,Gore,Hail,Ice,Imulsion,Ink,Interior,Light,LightFunction,Liquid,Locust,Mechanical,Metal,MuzzleFlash,Neutral,Optimization_Done,Optimization_ToDo,Optimization_NotNeeded,Organic,Riftworm,Rock,Roof,Sign,Sky,Smoke,Snow,Steam,Stone,Stranded,Tiling,Trash,Tree,Trim,Vehicle,Wall,Water,Weapon,Wood)))

[ScriptDatabase.Settings]
ListOfNodes=Admin,Cave,Cells,Garden,Max,Medical,Overworld,EnemyBarks

[BrowserData]
Prefab_ZoomFactor=1.00000

[FEditorModeTools]
TranslationMode=1

[Engine.ActorFactoryStaticMesh]
MenuPriority=20

[Engine.ActorFactoryMover]
MenuPriority=15

[UnrealEd.CustomPropertyItemBindings]
+CustomPropertyClasses=(PropertyPathName="Engine.LevelStreamingVolume:StreamingLevels", PropertyItemClassName="WxPropertyWindow_LevelList", bReplaceArrayHeaders=1)

; Allow us to ignore certain packages in the VerifySourceControl commandlet (must be sensible with this!!!)
[UnrealEd.VerifySourceIgnore]
+Package=EditorMaterials
+Package=EditorResources
+Package=EditorResources_Gfx
+Package=EngineResources
+Package=EngineMaterials
+Package=EngineVolumetrics
+Package=Engine_MI_Shaders
+Package=RockEditorResources
+Package=FlashTest
+Package=UE3UI
+Package=BMPanels
+Package=LC_AG4
+Package=LC_cop
+Package=LC_TZero
+Package=Brush_Demo
+Package=LeesPackage
+Package=MARK_TEST
+Package=NPC_Unarmed_Anims
+Package=Combat_Camera
+Package=Combat_vs_Thug_Anims
+Package=Batman_Ragdoll
+Package=Batman_PromoAnims
+Package=Character_Trash
+Package=Assault_Rifle
+Package=asylumtest
+Package=OutsourceTests
; Rockgame stuff
+Object=fx_misc.newspaper_t_BMtest
+Package=StormfuryStreet
+Package=Stormfurystreet2
+Package=stormfurystreet3
+Package=PRT_Stormfurysea
+Package=OBJ_Bouy
; Fonts are OK
+Package=BmFonts
+Package=BmFonts_Pol
+Package=BmFonts_Rus
; Ignoring FX_Weather as all the assets are available in Stormfury or are easily recreated
+Package=FX_Weather
; Tests for Outcast
+Package=LC_Pistol_Anims
+Package=LC_Unarmed_Anims
+Package=desert_eagle_3p
+Package=Machete_3P
+Package=Shotgun
+Package=Character_Trash
+Object=LIGHTS_Int.Lights_Int_LightBeam_falloff01_D
+Object=LIGHTS_Int.Lights_Int_LightBeam_fallof02_D
+Object=FX_Godrays.Godrays.FX_Godray_plane01_noise01_t
+Object=fx_smoke.ScarecrowRoom.fx_PlumeSmoke
+Object=fx_smoke.ScarecrowRoom.FX_fire1_noise_t
+Object=fx_smoke.ScarecrowRoom.FX_fire1_smoke_t
; Obsolete cinematics stuff from Jeff
+Package=Cinematic_Animations
; Contains obsolete UI references
+Package=FE
+Package=Menus
; NVIDIA packages
+Package=PX_Cloth_Medical
+Package=PX_Scarecrow2
+Package=PX_ClothRBTest
+Package=PX_ClothTest_TearLines
+Package=PX_Cloth_Paper
+Package=PX_Cloth_Draped
+Package=PX_Paper_Stacks
+Package=PX_Smoke
+Package=PX_Sparks
+Package=PX_Cloth_Hanging
+Package=PX_Cloth_Tape
+Package=PX_Dest_Medical_B7
+Package=PX_FX_Particles
+Package=PX_Cave_A_Dest
+Package=Nvidia_Physics
;It's trivial to recreate the camera as it's in all the max files with animated cameras
+Object=Cinematic_Camera.Camera_Rig.Cinematic_Camera_Rig
; Obsolete dialogue packages that reference deleted wavs
+Package=Speech-C2_Doctor1
+Package=Speech-C2_Dr_Jessop
+Package=Speech-C2_Guard2
+Package=Speech-C2_HeadOrderly
+Package=Speech-C2_Kerrison
+Package=Speech-AsylumTest01
+Package=Speech-AsylumTest02
+Package=Speech-C1_Batman
+Package=Speech-C1_NPC
+Package=Speech-EnemyTest
+Package=Speech-forensic_test
+Package=Speech-C2_Andy
+Package=Speech-C2_atmosphere
+Package=Speech-C2_Dr_Walker
+Package=Speech-C2_Dr_Young
+Package=Speech-C2_Guard1
+Package=Speech-C2_Guard3
+Package=Speech-C2_Guard4
+Package=Speech-C2_Guard5
+Package=Speech-C2_Guard6
+Package=Speech-C2_Guard7
+Package=Speech-C2_Inmate_B27
+Package=Speech-C2_Mental2
+Package=Speech-C2_Mental3
+Package=Speech-C2_Oracle
+Package=Speech-C2_Orderly1
+Package=Speech-C2_Scott
+Package=Speech-Promo
+Package=Speech-POZ_TEST
+Package=Speech-Test
+Object=IngmarTest.fx_BlueSea_Tex
+Object=Speech-Joker_Predator.Joker_Predator_automated_AnnounceTakedown-10
+Object=Speech-Scarecrow_Taunts.Scarecrow_Taunts_Death_Short_01-4
+Object=Speech-Venom_J.Venom_J_Attack_idles_04-3
+Object=Speech-Venom_J.Venom_J_Attack_idles_04-2
