/******************************************************************************/
/*                                                                            */
/*      © DARKWORKS, 2008-2009. Patent-pending technology by TRIOVIZ.         */
/*                                                                            */
/******************************************************************************/

#include "DwTriovizCommon.usf"

#ifndef NUM_SAMPLES
#define NUM_SAMPLES 3
#endif

float4 SampleOffsets[(NUM_SAMPLES + 1) / 2];

void Main(
	in float4 InPosition : POSITION,
	in float2 InUV : TEXCOORD0,
	out float4 OutOffsetUVs[(NUM_SAMPLES + 1) / 2] : TEXCOORD0,
	out float4 OutPosition : POSITION
	)
{
	OutPosition = InPosition;
	for(int OffsetIndex = 0;OffsetIndex < (NUM_SAMPLES + 1) / 2;OffsetIndex++)
	{
		OutOffsetUVs[OffsetIndex] = InUV.xyxy + SampleOffsets[OffsetIndex];
	}
}

void MainInit(
	in float4 InPosition : POSITION,
	in float2 InUV : TEXCOORD0,
	out float2 OutUV : TEXCOORD0,
	out float4 OutPosition : POSITION
	)
{
	OutPosition = InPosition;
	OutUV = InUV;
}

void AdaptedMinMaxMain(
	float2 InPosition : POSITION,
	out float4 OutPosition : POSITION
	)
{
	OutPosition = float4( InPosition, 0, 1 );
}

