/******************************************************************************/
/*                                                                            */
/*      © DARKWORKS, 2008-2009. Patent-pending technology by TRIOVIZ.         */
/*                                                                            */
/******************************************************************************/

#include "DwTriovizCommon.usf"

#ifndef NUM_SAMPLES
#define NUM_SAMPLES 16
#endif

sampler2D FilterTexture;

#if DWTRIOVIZ_ANY_GAME

	// For min/max depth reduction we can start with two different depth buffer.
	// - One fullscreen depth buffer in Inverted Z-device
	// (inverted Z device depth buffer on XBOX360 and encoded inverted Z device in alpha channel for PS3 and PC (EncodeFloatW function))
	// - One reduced depth buffer like the one used for ambient occlusion (depth encoded in Y channel in linear eye space)
	// So we must manage both here. But instead of doing the conversion in the first pass of the reduction algorithm and process them after
	// with similar code, we keep raw data, apply the reduction and convert in the final pass as an optimization.
	// So we need to keep min and max of each value at each step, but in case of inverted Z device value, we must swap to max and min.
	// This is the purpose of following macro
	#if DWTRIOVIZ_USE_DOWNSAMPLED_DEPTH
		#define COMPARE_MIN min
		#define COMPARE_MAX max
		#define INIT_VALUE_MIN_PASS DWTRIOVIZ_FLOAT_MAX
		#define INIT_VALUE_MAX_PASS DWTRIOVIZ_FLOAT_MIN
	#else // DWTRIOVIZ_USE_DOWNSAMPLED_DEPTH
		// We want to get min/max value of Z
		// We do this in Inverted Z Device space [1..0]. So test are inverted too.
		// Remember to init value in consequence (Max value is 0, not 1...)
		#define COMPARE_MIN max
		#define COMPARE_MAX min
		#define INIT_VALUE_MIN_PASS 0.0h
		#define INIT_VALUE_MAX_PASS 1.0h
	#endif // DWTRIOVIZ_USE_DOWNSAMPLED_DEPTH

	// See comment in DwTriovizCommon.usf for this macro
	#if DWTRIOVIZ_EXCLUDE_INFINITE_OBJECT
		// Due to float imprecision we can't just do == on DWTRIOVIZ_FLOAT_MAX
		// so subtract an epsilon to MAX FLOAT value (here we suppose FLOAT_MAX > 32000 for epsilon)
		// WARNING : epsilon (4.0h) really depends on game units !!!
		#define _DEPTH_THRESHOLD (DWTRIOVIZ_FLOAT_MAX - 4.0h)
		
		#if DWTRIOVIZ_USE_DOWNSAMPLED_DEPTH
			#define DEPTH_THRESHOLD _DEPTH_THRESHOLD
			#define COMPARE_THRESHOLD(X) (X >= DepthThreshold)
		#else
			// In invertZ device, convert DEPTH_THRESHOLD to [1..0] range based on projection matrix similar to what is done with EncodeFloatW
			#define DEPTH_THRESHOLD (MinZ_MaxZRatio[1] + MinZ_MaxZRatio[0] / _DEPTH_THRESHOLD)
			#define COMPARE_THRESHOLD(X) (X <= DepthThreshold)
		#endif // DWTRIOVIZ_USE_DOWNSAMPLED_DEPTH
	#endif // DWTRIOVIZ_EXCLUDE_INFINITE_OBJECT

#elif DWTRIOVIZ_IAA_SPECIFIC

	#if !DWTRIOVIZ_USE_DOWNSAMPLED_DEPTH && XBOX
		// We want to get min/max value of Z
		// We do this in Inverted Z Device space [1..0]. So test are inverted too.
		// Remember to init value in consequence (Max value is 0, not 1...)
		#define COMPARE_MIN max
		#define COMPARE_MAX min
		#define INIT_VALUE_MIN_PASS 0.0h
		#define INIT_VALUE_MAX_PASS 1.0h
	#else
		#define COMPARE_MIN min
		#define COMPARE_MAX max
		#define INIT_VALUE_MIN_PASS DWTRIOVIZ_FLOAT_MAX
		#define INIT_VALUE_MAX_PASS DWTRIOVIZ_FLOAT_MIN
	#endif

	// See comment in DwTriovizCommon.usf for this macro
	#if DWTRIOVIZ_EXCLUDE_INFINITE_OBJECT
		// Due to float imprecision we can't just do == on DWTRIOVIZ_FLOAT_MAX
		// so subtract an epsilon to MAX FLOAT value (here we suppose FLOAT_MAX > 32000 for epsilon)
		// WARNING : epsilon (4.0h) really depends on game units !!!
		#define _DEPTH_THRESHOLD (DWTRIOVIZ_FLOAT_MAX - 4.0h)

		#if !DWTRIOVIZ_USE_DOWNSAMPLED_DEPTH && XBOX
			// In invertZ device, convert DEPTH_THRESHOLD to [1..0] range based on projection matrix similar to what is done with EncodeFloatW
			#define DEPTH_THRESHOLD (MinZ_MaxZRatio[1] + MinZ_MaxZRatio[0] / _DEPTH_THRESHOLD)
			#define COMPARE_THRESHOLD(X) (X <= DepthThreshold)	
		#else
			#define DEPTH_THRESHOLD _DEPTH_THRESHOLD
			#define COMPARE_THRESHOLD(X) (X >= DepthThreshold)
		#endif
	#endif // DWTRIOVIZ_EXCLUDE_INFINITE_OBJECT

#endif

//-----------------------------------------------------------------------------
// Init downsample Min
//-----------------------------------------------------------------------------

void MainInitMin(
	in float2 InUV : TEXCOORD0,
	out float4 OutColor : COLOR0
	)
{
	OutColor = DwTriovizGetInvertZDevice(FilterTexture, InUV); 	// Duplicated Min in order to allow writing in the right channel with channel masking
}

//-----------------------------------------------------------------------------
// Init downsample Max
//-----------------------------------------------------------------------------

void MainInitMax(
	in float2 InUV : TEXCOORD0,
	out float4 OutColor : COLOR0
	)
{
	#if DWTRIOVIZ_EXCLUDE_INFINITE_OBJECT
	const half DepthThreshold = DEPTH_THRESHOLD;
	#endif // DWTRIOVIZ_EXCLUDE_INFINITE_OBJECT

	half Max = DwTriovizGetInvertZDevice(FilterTexture, InUV);
	#if DWTRIOVIZ_EXCLUDE_INFINITE_OBJECT
	Max = COMPARE_THRESHOLD(Max) ? INIT_VALUE_MAX_PASS : Max;
	#endif // DWTRIOVIZ_EXCLUDE_INFINITE_OBJECT

	OutColor = Max;	// Duplicated Max in order to allow writing in the right channel with channel masking
}

//-----------------------------------------------------------------------------
// Main downsample min/max shader
//-----------------------------------------------------------------------------

// Note that this reduction work on four channel
// xy == Min/??? of the whole scene (Note that we don't use Max)
// zw == Min/Max of the center of the scene
void Main(
	in float4 InOffsetUVs[(NUM_SAMPLES + 1) / 2] : TEXCOORD0,
	out float4 OutColor : COLOR0
	)
{
	half4	MinMax			= half4(INIT_VALUE_MIN_PASS, INIT_VALUE_MAX_PASS, INIT_VALUE_MIN_PASS, INIT_VALUE_MAX_PASS);
	half4	CurrentMinMax	= 0;

#if PS3 // Don't know why but standard code cause 
		// error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
		// on PS3. Dependency between variable seems to be a problem for sony compiler.
		// This should changed nothing, as all is unroll.
		// TODO : Test with future version of compile if this work
	for (int SampleIndex = 0; SampleIndex < NUM_SAMPLES - 1; SampleIndex += 2)
	{
		CurrentMinMax = DWTRIOVIZ_H4TEX2D(FilterTexture,InOffsetUVs[SampleIndex / 2].zw).xyzw;
		MinMax.xz = COMPARE_MIN(MinMax.xz, CurrentMinMax.xz);
		MinMax.yw = COMPARE_MAX(MinMax.yw, CurrentMinMax.yw);
	}

	for (int SampleIndex = 0; SampleIndex < NUM_SAMPLES - 1; SampleIndex += 2)
	{
		CurrentMinMax = DWTRIOVIZ_H4TEX2D(FilterTexture,InOffsetUVs[SampleIndex / 2].xy).xyzw;
		MinMax.xz = COMPARE_MIN(MinMax.xz, CurrentMinMax.xz);
		MinMax.yw = COMPARE_MAX(MinMax.yw, CurrentMinMax.yw);
	}
#else // PS3
	for (int SampleIndex = 0; SampleIndex < NUM_SAMPLES - 1; SampleIndex += 2)
	{
		CurrentMinMax = DWTRIOVIZ_H4TEX2D(FilterTexture,InOffsetUVs[SampleIndex / 2].xy).xyzw;
		MinMax.xz = COMPARE_MIN(MinMax.xz, CurrentMinMax.xz);
		MinMax.yw = COMPARE_MAX(MinMax.yw, CurrentMinMax.yw);

		CurrentMinMax = DWTRIOVIZ_H4TEX2D(FilterTexture,InOffsetUVs[SampleIndex / 2].zw).xyzw;
		MinMax.xz = COMPARE_MIN(MinMax.xz, CurrentMinMax.xz);
		MinMax.yw = COMPARE_MAX(MinMax.yw, CurrentMinMax.yw);
	}
#endif // PS3

	if (NUM_SAMPLES % 2) // if odd
	{
		CurrentMinMax = DWTRIOVIZ_H4TEX2D(FilterTexture,InOffsetUVs[(NUM_SAMPLES - 1) / 2].xy).xyzw;
		MinMax.xz = COMPARE_MIN(MinMax.xz, CurrentMinMax.xz);
		MinMax.yw = COMPARE_MAX(MinMax.yw, CurrentMinMax.yw);
	}

	OutColor = MinMax;
}

//-----------------------------------------------------------------------------
// ProcessAdaptedMinMax
//-----------------------------------------------------------------------------

float4			AdaptedMinMaxParam;

static float	ElapsedTime						= AdaptedMinMaxParam.x;
static float	DisparityLevel					= AdaptedMinMaxParam.z;

#if DWTRIOVIZ_TEST_WITH_CONSTANT_PARAMETERS
#define			AdaptationSpeed					0.25f
#define			OverrideDefaultDisparityLevel	0.0f
#else // DWTRIOVIZ_TEST_WITH_CONSTANT_PARAMETERS
static float	AdaptationSpeed					= AdaptedMinMaxParam.y;
static float	OverrideDefaultDisparityLevel	= AdaptedMinMaxParam.w;
#endif // DWTRIOVIZ_TEST_WITH_CONSTANT_PARAMETERS

sampler			MinMaxTexture;
sampler2D		LastAdaptedMinMaxTexture;

// Don't matter the cost of this pixel, as it is executed only for one pixel.
float4 ProcessAdaptedMinMax() : COLOR
{
	// LastAdaptedMinMaxTexture has the following specification (LargeMin, CenterMax, SmoothedDisparityLevel, OriginalDisparityLevel)
	// We keep original DisparityLevel for debug purpose.
	float4 AdaptedMinMax = tex2D(LastAdaptedMinMaxTexture, float2(0.5f, 0.5f));
	
	// MinMaxTexture has the following specification (LargeMin, Unused, CenterMin, CenterMax)
	// Which we convert in CurrentMinMax to (LargeMin, CenterMax, DisparityLevel, DisparityLevel)
    float4 CurrentMinMax = tex2D(MinMaxTexture, float2(0.5f, 0.5f)).xwzz; 

#if DWTRIOVIZ_ANY_GAME

	#if !DWTRIOVIZ_USE_DOWNSAMPLED_DEPTH
		// Convert from Inverted Z Device space to linear eye space and clamp to [0..DWTRIOVIZ_FLOAT_MAX] See DwTriovizCommon.usf comment
		// Remeber on XBOX, Unreal engine code in MSAA mode do a - 0.000001
		// But instead of adding + 0.000001 we just handle infinite negative depth with abs(), this allow to manage no-MSAA code too.
		CurrentMinMax.xyz = min(abs(half3(ConvertFromDeviceZ(CurrentMinMax.x), ConvertFromDeviceZ(CurrentMinMax.y), ConvertFromDeviceZ(CurrentMinMax.z))), DWTRIOVIZ_FLOAT_MAX);
	#endif // !DWTRIOVIZ_USE_DOWNSAMPLED_DEPTH

#elif DWTRIOVIZ_IAA_SPECIFIC

	#if !DWTRIOVIZ_USE_DOWNSAMPLED_DEPTH && XBOX
		// Convert from Inverted Z Device space to linear eye space and clamp to [0..DWTRIOVIZ_FLOAT_MAX] See DwTriovizCommon.usf comment
		// Remeber on XBOX, Unreal engine code in MSAA mode do a - 0.000001
		// But instead of adding + 0.000001 we just handle infinite negative depth with abs(), this allow to manage no-MSAA code too.
		CurrentMinMax.xyz = min(abs(half3(ConvertFromDeviceZ(CurrentMinMax.x), ConvertFromDeviceZ(CurrentMinMax.y), ConvertFromDeviceZ(CurrentMinMax.z))), DWTRIOVIZ_FLOAT_MAX);
	#endif

#endif

	// Required code when other shader do something bad (like putting a wrong value in depth or color buffer)... To prevent propagating error.
	// This contribute to DwTrioviz robustness.
	AdaptedMinMax = isnan(AdaptedMinMax) ? float4(1.0f,DWTRIOVIZ_FLOAT_MAX,1000.0f,1.0f) : AdaptedMinMax;
	CurrentMinMax = isnan(CurrentMinMax) ? float4(1.0f,DWTRIOVIZ_FLOAT_MAX,1000.0f,1.0f) : CurrentMinMax;

	// If manual focal plane is required, take its value, else take automatic collimation plane based on CenterMin
	// We will do a smooth transition
	CurrentMinMax.z = lerp(CurrentMinMax.z, DisparityLevel, OverrideDefaultDisparityLevel);

	// If DisparityLevel is inferior to Max of the center, set Max to this value (only happen in override case)
	// DWTRIOVIZ_EXCLUDE_INFINITE_OBJECT comment
	// Here we manage the specific case where we want to exclude infinite object but we have only infinite object in focal region.
	// So Max will be set to INIT_VALUE_MAX_PASS and CenterMax < CenterMin
	// If this is the case, set disparity level and CenterMax to the same value
	// end DWTRIOVIZ_EXCLUDE_INFINITE_OBJECT
	// Both case are handled by same following code
	CurrentMinMax.y = max(CurrentMinMax.y, CurrentMinMax.z);

    // The user's adapted minmax level is simulated by closing the gap between
    // adapted minmax and current minmax by 2% every frame, based on a 30 fps
    // rate
	// Note : Here .w component are not used
    float4 NewAdaptation = AdaptedMinMax + (CurrentMinMax - AdaptedMinMax) * ( 1 - pow( 1.0f - AdaptationSpeed, 30 * ElapsedTime ) );
	NewAdaptation.w = CurrentMinMax.z; // Use only for debug

	return NewAdaptation; // (LargeMin, CenterMax, SmoothedDisparityLevel, OriginalDisparityLevel)
}
