/******************************************************************************/
/*                                                                            */
/*      © DARKWORKS, 2008-2009. Patent-pending technology by TRIOVIZ.         */
/*                                                                            */
/******************************************************************************/

#include "DwTriovizCommon.usf"

#ifndef NUM_SAMPLES
#define NUM_SAMPLES 4
#endif

/** The offsets used to sample the scene texture. */
float4 SampleOffsets[(NUM_SAMPLES + 1) / 2];

/** The entry point. */
void Main(
	in float4 InPosition : POSITION,
	in float2 InUV : TEXCOORD0,
	out float4 OutOffsetUVs[(NUM_SAMPLES + 1) / 2] : TEXCOORD0,
	out float4 OutPosition : POSITION
	)
{
	OutPosition = InPosition;
	for(int OffsetIndex = 0;OffsetIndex < (NUM_SAMPLES + 1) / 2;OffsetIndex++)
	{
		OutOffsetUVs[OffsetIndex] = InUV.xyyx + SampleOffsets[OffsetIndex];
	}
}

