/******************************************************************************/
/*                                                                            */
/*      © DARKWORKS, 2008-2009. Patent-pending technology by TRIOVIZ.         */
/*                                                                            */
/******************************************************************************/

#include "DwTriovizCommon.usf"

void ZToDMapVertexMain(
	in float4 InPosition : POSITION,
	in float2 InTexCoord : TEXCOORD0,
	out float2 OutTexCoord0 : TEXCOORD0,
	out float2 OutPos : TEXCOORD1,
	out float4 OutPosition : POSITION
	)
{
	OutPosition		= InPosition;
	OutTexCoord0	= InTexCoord;
	OutPos			= InPosition.xy;
}

half4 SceneCoordinateScaleBias;
void VertexMain(
	float4 InPosition : POSITION,
	float2 InScreenUV : TEXCOORD0,
	out float2 OutSceneUV : TEXCOORD0,
#if DWTRIOVIZ_USE_SEPARATE_DMAPUV	
	out float2 OutDMapUV : TEXCOORD1,
#endif	
	out float4 OutPosition : POSITION
	)
{
	OutPosition		= InPosition;								// Target position
	float2 SceneUV	= InPosition.xy / InPosition.w * SceneCoordinateScaleBias.xy + SceneCoordinateScaleBias.wz;
	OutSceneUV		= SceneUV;									// Background UV for SceneColor
#if DWTRIOVIZ_USE_SEPARATE_DMAPUV	
	OutDMapUV		= InScreenUV;								// UV for DMap texture
#endif	
}


