/******************************************************************************/
/*                                                                            */
/*      © DARKWORKS, 2008-2009. Patent-pending technology by TRIOVIZ.         */
/*                                                                            */
/******************************************************************************/

// Shared file for DwTrioviz

#include "Common.usf"


//-----------------------------------------------------------------------------
// Managing Video PostProcessing
//-----------------------------------------------------------------------------
#ifndef DWTRIOVIZ_VIDEO
#define DWTRIOVIZ_VIDEO			0
#endif


//-----------------------------------------------------------------------------
// Managing Specific Games
//-----------------------------------------------------------------------------
#define DWTRIOVIZ_IAA_SPECIFIC			0
#define DWTRIOVIZ_ANY_GAME				!(DWTRIOVIZ_IAA_SPECIFIC)

// ConvertFromDeviceZ was not defined in older QAs !
// Note that ConvertToClipSpaceW is only defined when SUPPORTS_DEPTH_TEXTURES
// Here we also define the channel that stores depth values in the downsampled depth texture
#if DWTRIOVIZ_ANY_GAME
	#define DEPTH_TEXTURE_CHANNEL	y
#elif DWTRIOVIZ_IAA_SPECIFIC
	#define DEPTH_TEXTURE_CHANNEL	x
	#if SUPPORTS_DEPTH_TEXTURES
		#define ConvertFromDeviceZ		ConvertToClipSpaceW
	#endif		
#endif


//-----------------------------------------------------------------------------
// Global Optim :
// On PS3 using old CG compiler, we deactivate optims since optimized version is slower than not optimized version...
// This is due to the compiler, which can't re-order properly instructions (because of less instruction number)
// We will have to check for perf with new compiler version
//-----------------------------------------------------------------------------
#if PS3
	#if __CGC__ < 20000
		#define DWTRIOVIZ_FULLY_OPTIMIZED 0
	#else
		#define DWTRIOVIZ_FULLY_OPTIMIZED 1
	#endif
#else
	#define DWTRIOVIZ_FULLY_OPTIMIZED 1
#endif

//-----------------------------------------------------------------------------
// Optim : On console we use SceneUV as DMapUV
//-----------------------------------------------------------------------------
#if XBOX || PS3
	#if DWTRIOVIZ_FULLY_OPTIMIZED
		#define DWTRIOVIZ_USE_SEPARATE_DMAPUV 0
	#else
		#define DWTRIOVIZ_USE_SEPARATE_DMAPUV 1
	#endif
#else
	#define DWTRIOVIZ_USE_SEPARATE_DMAPUV 1
#endif

//-----------------------------------------------------------------------------
// PS3 Optim : use hntex2D whenever it is possible
//-----------------------------------------------------------------------------
#if PS3
	#define DWTRIOVIZ_H1TEX2D h1tex2D
	#define DWTRIOVIZ_H2TEX2D h2tex2D
	#define DWTRIOVIZ_H3TEX2D h3tex2D
	#define DWTRIOVIZ_H4TEX2D h4tex2D

	#if DWTRIOVIZ_ANY_GAME
		half3 _CalcSceneColor(float2 ScreenUV)
		{
			/// Must be the same content as original CalcSceneColor in Common.usf
			return DWTRIOVIZ_H3TEX2D(SceneColorTexture,ScreenUV).rgb;
		}
		#define CalcSceneColor _CalcSceneColor

		half _CalcSceneDepth(float2 ScreenUV)
		{
			/// Must be the same content as original CalcSceneDepth in Common.usf
			return ConvertFromDeviceZ(DWTRIOVIZ_H4TEX2D(SceneColorTexture,ScreenUV).a);
		}
		#define CalcSceneDepth _CalcSceneDepth
	#endif
#else	// PS3
	#define DWTRIOVIZ_H1TEX2D tex2D
	#define DWTRIOVIZ_H2TEX2D tex2D
	#define DWTRIOVIZ_H3TEX2D tex2D
	#define DWTRIOVIZ_H4TEX2D tex2D
#endif	// PS3


//-----------------------------------------------------------------------------
// Quality control (Enable it has performance impact)
//-----------------------------------------------------------------------------

// Separate DOF calculation for left and right eye
// If not enabled, in case of strong dof we can have some wrong halo created around far object
// but with default value we don't need it
#define DWTRIOVIZ_SEPARATE_DOF 0

// This define allow to manage the prescence of very var object suppose to be set at infinite, like the sky
// (Sky is often represented in game with a very far skydome).
// Infinite object can cause problem when it is in the region used for the reduced min/max algorithm.
// In this case we can loose precision of the 3D effect due to the large depth range to manage. We want to avoid this inefficient 3D experience
// by avoiding to take infinite object into account. For this we use specific code and suppose that the infinite object is at DWTRIOVIZ_FLOAT_MAX (see comment below)
// All objects at a depth of DWTRIOVIZ_FLOAT_MAX or above won't change the depth range used for the DMap construction.
// Note that we support the case where there is only infinite object in focal region. In this case, the focal plane is on infinite object.
// If there are no objects above DWTRIOVIZ_FLOAT_MAX depth this define should be disabled.
#define DWTRIOVIZ_EXCLUDE_INFINITE_OBJECT 0

//-----------------------------------------------------------------------------
// Hardware specific note
//-----------------------------------------------------------------------------

// Hardware note
// RSX is an NVIDIA card with following specification:
// - Support 16f Industrial light and Magic - the "half type" - with nan and inf for both shader and framebuffer
// - 16f MAX_FLOAT value +/- 65504
// XBOX360 is an ATI card with following specification:
// - No half in shader, only float (so half are treated as float)
// - 16f framebuffer support value +/- 131008 and don't have nan or inf
// Specific to XBOX for 16F format
// The GPU cannot directly perform bilinear filtering of 16-bit floats (or any other floats).
// It does implement, however, a restricted kind of filtering for formats with _EXPAND in their names.
// These textures are first expanded to a signed 15.16 fixed point form, and then interpolated.
// In practice this mean that that range of [-131008..131008] is convert to -32768, 32767.998

// So to avoid any problem with limits on all these platform, we just clamp any value to 0..32767 (Which can be replace by a min only)
// This will be perfect for Trioviz and allow to work in the same way with same value in same range.
#define DWTRIOVIZ_FLOAT_MIN 0.0h
#define DWTRIOVIZ_FLOAT_MAX 32767.0h

// A XBOX360 problem with Unreal engine:
// Unreal engine use an infinite projection matrix with a Z_PRECISION of 0.001f (UnMath.h) this mean that infinite object will be mapped to 0.999f in z buffer
// and with inverted z buffer on XBOX360, this will be mapped to 0.001f
// However for the XBOX360 when MSAA is enabled which require the use of predicated tiling, we need to restore the color and depth buffer.
// In the RHIRestoreColorDepth implementation for XBOX360 we have a specific code "return tex2D(DepthTex, Tex.xy).x-0.000001;"
// So any z device restored value are biased.
// From Niklas Smedberg on UDN mailing list
// "I believe the reason for the -0.000001 is in RHIRestoreColorDepth() is to compensate for losing information in the conversion from an MSAA depth buffer
// to non-MSAA depth buffer. During the conversion (at Resolve time) we only grab 1 of the 4 depth samples and we want any future depth-testing with the
// non-MSAA depth buffer to be conservative, so we push all depth values away from the camera a tiny bit."
// So, when an object is near infinite, like a skydome, it should be mapped to 0.001f on XBOX360.
// Normaly, we don't reach such a small value even for large number, but when your skydome is at 10 000 000, you can reach it (and believe me designer are able
// to do such kind of dumb thing). In our TestBed we get an object at 0.001000648.
// With the default unreal engine matrix with near plane at 10. We get a value of 0.0009999648 (= 0.001000648 - 0.000001) in restored z device
// which create a value of ConvertFromDeviceZ(0.0009999648) = -4.47e8 for eye linear space z value which is clamped to -131008.
// To avoid this problem of negative value we just redefine CalcSceneDepth to get the abs of the value

//-----------------------------------------------------------------------------
// Macro to manage the use of a Downsampled Depth instead of standard Z buffer
//-----------------------------------------------------------------------------

#ifndef DWTRIOVIZ_USE_DOWNSAMPLED_DEPTH
#define DWTRIOVIZ_USE_DOWNSAMPLED_DEPTH 0
#endif

// We have a game based on an old QA, that uses X channel to store depth value in depth texture
// So we set the DEPTH_TEXTURE_CHANNEL as follow, but this really depends on your game param !

#if DWTRIOVIZ_USE_DOWNSAMPLED_DEPTH

	// With Unreal engine the downsampled depth texture is the ambient occlusion texture.
	// The depth value is store in Y component of a R16G16F texture.
	// Note : this texture use the max of depth sample instead of the min to avoid artifact for ambient occlusion.
	// Normally Trioviz should use the min of the depth sample, but this seems not to be a problem.
	// Tranform has already been done to recover linear eye depth. So we can have -131008 in the Z value. As this is the only
	// negative value we can get, just take abs. See above note for details.
	#define DwTriovizSampleDepth(X,Y) min(abs(DWTRIOVIZ_H2TEX2D(X,Y).DEPTH_TEXTURE_CHANNEL), DWTRIOVIZ_FLOAT_MAX)

#else

	// When using the standard depth texture, we use the standard way to recover the depth
	// Normally we should take the min of the N depth sample around our pixel to get a correct
	// Depth value for ZToDmap pass (Where N is the square of the downsample factor).
	// We only take the first depth sample, difference in quality are negligible.
	// See comment above
	
	#if (DWTRIOVIZ_VIDEO && XBOX)
		half _CalcSceneDepth(float2 ScreenUV)
		{
			/// Must be the same content as original CalcSceneDepth in Common.usf
			return ConvertFromDeviceZ(DWTRIOVIZ_H4TEX2D(SceneColorTexture,ScreenUV).a);
		}
		#define DwTriovizSampleDepth(X,Y) min(abs(_CalcSceneDepth(Y)), DWTRIOVIZ_FLOAT_MAX)
	#else
		#define DwTriovizSampleDepth(X,Y) min(abs(CalcSceneDepth(Y)), DWTRIOVIZ_FLOAT_MAX)
	#endif	

#endif

#if DWTRIOVIZ_USE_DOWNSAMPLED_DEPTH

	#define DwTriovizGetInvertZDevice(X, Y) min(abs(DWTRIOVIZ_H2TEX2D(X,Y).DEPTH_TEXTURE_CHANNEL), DWTRIOVIZ_FLOAT_MAX)

#else

	// All Z device for each platform in Unreal engine are store inverted (1 - z_device)
	#if DWTRIOVIZ_VIDEO
		#define DwTriovizGetInvertZDevice(X, Y) DWTRIOVIZ_H4TEX2D(SceneColorTexture,Y).a
	#elif SUPPORTS_DEPTH_TEXTURES
		#define DwTriovizGetInvertZDevice(X, Y) texDepth2D(SceneDepthTexture,Y).r
	#elif SM2_PROFILE
		#define DwTriovizGetInvertZDevice(X, Y) DWTRIOVIZ_H4TEX2D(SceneDepthTexture,Y).a
	#else
		#if DWTRIOVIZ_ANY_GAME
			#define DwTriovizGetInvertZDevice(X, Y) DWTRIOVIZ_H4TEX2D(SceneColorTexture,Y).a
		#elif DWTRIOVIZ_IAA_SPECIFIC
			#define DwTriovizGetInvertZDevice(X, Y) min(DWTRIOVIZ_H4TEX2D(SceneColorTexture,Y).a, DWTRIOVIZ_FLOAT_MAX)
		#endif
	#endif

#endif

//-----------------------------------------------------------------------------
// Perf Check : We use a define to compare constant vs dynamic parameters in trioviz shaders
// Note this is only for testing so this should always be set to zero in game
//-----------------------------------------------------------------------------

#define DWTRIOVIZ_TEST_WITH_CONSTANT_PARAMETERS 0

#if DWTRIOVIZ_TEST_WITH_CONSTANT_PARAMETERS
	#define ConstantMultiplier 1.5h
	#define PercentFactorForeground (ConstantMultiplier * 0.003125h)
	#define PercentFactorBackground PercentFactorForeground
#endif // DWTRIOVIZ_TEST_WITH_CONSTANT_PARAMETERS


//-----------------------------------------------------------------------------
// Utility
//-----------------------------------------------------------------------------

half LevelsControl(half Value, half MinInput, half MaxInput, half Gamma)
{
	// Adjust usable range
	Value = min(max(Value - MinInput, 0.0f) / (MaxInput - MinInput), 1.0f);

	// Apply gamma
	return pow(Value, Gamma);
}

half2 LevelsControl(half2 Value, half MinInput, half MaxInput, half Gamma)
{
	// Adjust usable range
	Value = min(max(Value - MinInput, 0.0f) / (MaxInput - MinInput), 1.0f);

	// Apply gamma
	return pow(Value, Gamma);
}

half LevelsControlWithOuput(half Value, half MinInput, half MaxInput, half Gamma, half MinOuput, half MaxOutput)
{
	return lerp(MinOuput, MaxOutput, LevelsControl(Value, MinInput, MaxInput, Gamma));
}

half PointOnBezierCurve_01(half t1, half P1, half P2)
{
	/// Bernstein Polynomial Form : x(t) = aP0 + bP1 + cP2 + dP3
	/// In our special use : P0(0,0) and P3(1,1) are constant (i.e. aP0=0 , dP3=d)
	// a = (1-t)^3
	// b = 3t(1-t)^2
	// c = 3t^2(1-t)
	// d = t^3
	
	half t2 = t1*t1;
	half t3 = t1*t2;

	half OneMinusT = (1.0h - t1);
	half OneMinusTs = OneMinusT * OneMinusT;

	half P1t = 3.0h * t1 * OneMinusTs;
	half P2t = 3.0h * t2 * OneMinusT;
	half P3t = t3;

	half Y = P1 * P1t + P2 * P2t + P3t;
	
	return Y;
}

half LevelsControl_Bezier(half Value, half MinInput, half MaxInput, half2 P1, half2 P2)
{
	// Adjust usable range
	half t = min(max(Value - MinInput, 0.0f) / (MaxInput - MinInput), 1.0f);

	// Use X coord of point of curve as new input 
	//t = PointOnBezierCurve_01(t, P1.x, P2.x);
	
	// Get the matching Y coord 	
	half Y = PointOnBezierCurve_01(t, P1.y, P2.y);
	
	Y = saturate(Y);
	
	return Y;
}

half LevelsControl_BezierWithOuput(half Value, half MinInput, half MaxInput, half MinOuput, half MaxOutput, half2 P1, half2 P2)
{
	return lerp(MinOuput, MaxOutput, LevelsControl_Bezier(Value, MinInput, MaxInput, P1, P2));
}

//-----------------------------------------------------------------------------
// Utility macro
//-----------------------------------------------------------------------------

// There is two method to reconstruct left and right image

// Right eye and reconstruct left eye
// This macro was defined in case you want to use right eye and reconstruct only left eye
// But with antighost system we can't use it anymore
//#define RIGHT_OFFSET(V)		(0.0h)
//#define LEFT_RIGHT_FACTOR		(1.0h)

// Reconstruct left and right eye
#define RIGHT_OFFSET(V)			(-LeftOffset.V) // RightOffset is inverse of LeftOffset
#define LEFT_RIGHT_FACTOR		(0.5h)

//-----------------------------------------------------------------------------
// Color Correction to apply on input image, in our case on dof image and input image
//-----------------------------------------------------------------------------

// The per-color weighting to be used for luminance calculations in RGB order
static const half3 LUMINANCE_VECTOR = half3(0.212671f, 0.715160f, 0.072169f);

#if DWTRIOVIZ_COLOR_CORRECTION	
sampler3D DwTriovizColorCorrectionTexture;
#endif	

half3 ApplyColorCorrection(half3 Color)
{
#if DWTRIOVIZ_COLOR_CORRECTION	
	#if SM4_PROFILE
		Color =	tex3D(DwTriovizColorCorrectionTexture, float4(Color, 0.f)).bgra;
	#else
		Color =	tex3D(DwTriovizColorCorrectionTexture, float4(Color, 0.f));
	#endif
#endif

	return Color;
}


//-----------------------------------------------------------------------------
// DOF
//-----------------------------------------------------------------------------

// The packed parameters
half4 PackedParameters;

#if DWTRIOVIZ_TEST_WITH_CONSTANT_PARAMETERS
#define InverseFocusRadius		1.0h
#define FocusExponent			4.0h
#else // DWTRIOVIZ_TEST_WITH_CONSTANT_PARAMETERS
static half InverseFocusRadius	= PackedParameters.g;	// One over the minimum distance from the focal which is 0% focused
static half FocusExponent		= PackedParameters.b;	// The focus falloff exponent
#endif // DWTRIOVIZ_TEST_WITH_CONSTANT_PARAMETERS

// clamp for min/max blur amount values - default would be [1,1]
half2 MinMaxBlurClamp;

#if DWTRIOVIZ_TEST_WITH_CONSTANT_PARAMETERS
#define MaxNearBlurAmount		0.35h
#define MaxFarBlurAmount		0.2h
#else // DWTRIOVIZ_TEST_WITH_CONSTANT_PARAMETERS
static half MaxNearBlurAmount	= MinMaxBlurClamp.x;
static half MaxFarBlurAmount	= MinMaxBlurClamp.y;
#endif // DWTRIOVIZ_TEST_WITH_CONSTANT_PARAMETERS

// Computes the unfocused percent for a DMap value.
half CalcUnfocusedPercent(half DMapValue)
{
	// DMapValue is between [0..1], so transform it to [-1..1]
	// Blur amount based on ratio of distance to focus plane to the focus radius
	// it is clamped to [-1,1]. Note that FocusDistance can be negative if it 
	// falls behind the near plane.
	half RelativeDistance = -(2.0h * DMapValue - 1.0h); // Swap sign in order to get RelativeDistance < 0 be the foreground (remember, if Dmap > 0 => Foreground)
	half MaxUnfocusedPercent = RelativeDistance < 0 ? MaxNearBlurAmount : MaxFarBlurAmount;
	return min( MaxUnfocusedPercent, pow( saturate(abs(RelativeDistance) * InverseFocusRadius), FocusExponent ) );
}

half2 CalcUnfocusedPercent(half2 DMapValue)
{
#if DWTRIOVIZ_FULLY_OPTIMIZED
	half2 RelativeDistance = -(2.0h * DMapValue - 1.0h); // Swap sign in order to get RelativeDistance < 0 be the foreground (remember, if Dmap > 0 => Foreground)
	half2 MaxUnfocusedPercent = RelativeDistance < 0 ? MaxNearBlurAmount.xx : MaxFarBlurAmount.xx;
	return min( MaxUnfocusedPercent, pow( saturate(abs(RelativeDistance) * InverseFocusRadius), FocusExponent ) );
#else
	return half2(CalcUnfocusedPercent(DMapValue.x), CalcUnfocusedPercent(DMapValue.y));
#endif
}

