/*=============================================================================
	ModShadowVolumePixelShader.usf: Pixel shader for modulated shadow volumes
	Copyright 1998-2008 Epic Games, Inc. All Rights Reserved.
=============================================================================*/

#include "Common.usf"
#include "ModShadowCommon.usf"

void Main(
	in float4 ScreenPosition : TEXCOORD0,
// NVCHANGE_BEGIN: Stereo fixes
#if NV_STEREO_FIXES
	in float2 vPos : VPOS,
#endif // NV_STEREO_FIXES
// NVCHANGE_END: Stereo fixes
	out float4 OutColor : COLOR0
	)
{
// NVCHANGE_BEGIN: Stereo fixes
#if NV_STEREO_FIXES
	float4 TrueScreenPosition = VPosToClip(vPos);
#else // NV_STEREO_FIXES
	float4 TrueScreenPosition = ScreenPosition;
#endif // NV_STEREO_FIXES
	half SceneW = PreviousDepth(TrueScreenPosition);
// NVCHANGE_END: Stereo fixes

#if MODSHADOW_LIGHTTYPE_DIRECTIONAL
	// no attenuation necessary for directional lights
	half ShadowAtt = 1;
#else
	// attenuate between shadow color and white based on distance
	half ShadowAtt = ShadowAttenuation(ScreenPosition,SceneW);
#endif

	// add modulated/attenuated shadow color to shadow
	float4 ShadowedColor = lerp(float4(1,1,1,1),ShadowModulateColor,ShadowAtt);
	// RETURN_COLOR not needed with modulative blending
	OutColor = ShadowedColor;
}
