/*=============================================================================
	OcclusionQueryVertexShader_PS3.hlsl: Vertex shader for drawing occlusion queries.
	Copyright 1998-2008 Epic Games, Inc. All Rights Reserved.
=============================================================================*/

#include "Common.usf"


//@ROCK - ERG PJL for PS3 Instanced occlusion primitives
void Main(

#if PS3
	in float3 InPosition : ATTR0,
	in float3 PrimitiveOrigin : ATTR1,
	in float3 PrimitiveExtent: ATTR2,
#else
	in float3 InPosition : POSITION,
	in float3 PrimitiveOrigin :TEXCOORD0,
	in float3 PrimitiveExtent :TEXCOORD1,

#endif
	out float4 OutPosition : POSITION

)
{
	float3 CalculatedPosition = (InPosition * PrimitiveExtent) + PrimitiveOrigin.xyz;
	OutPosition = MulMatrix(ViewProjectionMatrix, float4(CalculatedPosition,1.0f) );
}
