#include "Common.usf"

float4 Parameters;
sampler2D SceneColorFullResTexture;
sampler2D SceneColorLowResTexture;

void Main(
	in float2 UV : TEXCOORD0,
	out float4 OutColor : COLOR0
	)
{
	float TexelSize = Parameters.xy;
	float DepthThreshold = Parameters.z;

	float minz = 1.e8;
	float maxz = 0.0;
	float FilterRadius = 1;

	UNROLL for (float x = -FilterRadius; x <= FilterRadius; ++x)
	{
		UNROLL for (float y = -FilterRadius; y <= FilterRadius; ++y)
		{
		    	float z = tex2D(SceneColorFullResTexture, UV + TexelSize * float2(x,y)).a;
			minz = min(z,minz);
			maxz = max(z,maxz);
		}
	}
	if (maxz - minz > DepthThreshold) discard;
	
	half4 SceneColor = tex2D(SceneColorLowResTexture,UV);
	OutColor = RETURN_COLOR(SceneColor);
}
