#include "Common.usf"

float4 Parameters;
sampler2D SceneColorFullResPointTexture;
sampler2D SceneColorLowResPointTexture;
sampler2D SceneColorLowResBilinearTexture;
sampler2D SceneDepthLowResPointTexture;

void UpdateNearestSample(inout float MinDist,
			 inout float2 NearestUV,
			 float Z,
			 float2 UV,
			 float ZFull)
{
	float Dist = abs(Z - ZFull);
	if (Dist < MinDist)
	{
		MinDist = Dist;
		NearestUV = UV;
	}
}

float FetchLowResDepth(float2 UV, float MaxViewZ)
{
	return min(ConvertFromDeviceZ(tex2D(SceneDepthLowResPointTexture, UV).a), MaxViewZ);
}

float FetchFullResDepth(float2 UV, float MaxViewZ)
{
	return min(ConvertFromDeviceZ(tex2D(SceneColorFullResPointTexture, UV).a), MaxViewZ);
}

void Main(
	in float2 InUV : TEXCOORD0,
	out float4 OutColor : COLOR0
	)
{
	float2 LowResTexelSize = Parameters.xy;
	float DepthThreshold = Parameters.z;
	float MaxViewZ = Parameters.w;

	float ZFull = FetchFullResDepth(InUV, MaxViewZ);

	float MinDist = 1.e8f;
	float2 NearestUV = InUV;	
	
	float2 UV = InUV - LowResTexelSize * 0.5;
	float Z00 = FetchLowResDepth(UV, MaxViewZ);
	UpdateNearestSample(MinDist, NearestUV, Z00, UV, ZFull);
	
	float2 UV10 = float2(UV.x+LowResTexelSize.x, UV.y);
	float Z10 = FetchLowResDepth(UV10, MaxViewZ);
	UpdateNearestSample(MinDist, NearestUV, Z10, UV10, ZFull);

	float2 UV01 = float2(UV.x, UV.y+LowResTexelSize.y);
	float Z01 = FetchLowResDepth(UV01, MaxViewZ);
	UpdateNearestSample(MinDist, NearestUV, Z01, UV01, ZFull);
	
	float2 UV11 = UV + LowResTexelSize;
	float Z11 = FetchLowResDepth(UV11, MaxViewZ);
	UpdateNearestSample(MinDist, NearestUV, Z11, UV11, ZFull);
	
	BRANCH
	if (abs(Z00 - ZFull) < DepthThreshold &&
	    abs(Z10 - ZFull) < DepthThreshold &&
	    abs(Z01 - ZFull) < DepthThreshold &&
	    abs(Z11 - ZFull) < DepthThreshold)
	{
		OutColor = tex2Dlod(SceneColorLowResBilinearTexture, float4(InUV,0,0));
	}
	else
	{
		OutColor = tex2Dlod(SceneColorLowResPointTexture, float4(NearestUV,0,0));
	
	}
}
