#include "Common.usf"

#define M_PI 3.1415926535897932384626433832795

float2 TexelSize;
sampler2D ShadowOSMTexture0;
sampler2D ShadowOSMTexture1;
sampler2D ShadowOSMTexture2;
sampler2D ShadowOSMTexture3;

void FilterOSMVertexMain(
	in float4 InPosition : POSITION,
	in float2 InTexCoord : TEXCOORD0,
	out float2 OutTexCoord0 : TEXCOORD0,
	out float4 OutPosition : POSITION
	)
{
	OutPosition = InPosition;
	OutTexCoord0 = InTexCoord;
}

void GenerateOSMPixelMain(
	in float2 TexCoord : TEXCOORD0,
	out float4 OutColor0 : COLOR0,
	out float4 OutColor1 : COLOR1,
	out float4 OutColor2 : COLOR2,
	out float4 OutColor3 : COLOR3
	)
{
	float4 InColor0 = tex2D( ShadowOSMTexture0, TexCoord );
	float4 InColor1 = tex2D( ShadowOSMTexture1, TexCoord );
	float4 InColor2 = tex2D( ShadowOSMTexture2, TexCoord );
	float4 InColor3 = tex2D( ShadowOSMTexture3, TexCoord );
	
	// These constants need to be applied as the result of integration
	float recipPi = 1.f/M_PI;
	float halfRecipPi = recipPi * 0.5f;
	float thirdRecipPi = recipPi/3.f;
	float quarterRecipPi = recipPi * 0.25f;
	float fifthRecipPi = recipPi * 0.2f;
	float sixthRecipPi = recipPi/6.f;
	float seventhRecipPi = recipPi/7.f;
	
	float lnColorMult = InColor0.y > 0.001f ? InColor0.x/InColor0.y : 0.f;
	
	OutColor0 = float4(lnColorMult, InColor0.y, InColor0.zw * recipPi);
	OutColor1 = float4(InColor1.xy * halfRecipPi, InColor1.zw * thirdRecipPi);
	
	/*
	5 coeffs only...
	OutColor2 = float4(InColor2.xy * quarterRecipPi, InColor2.zw * fifthRecipPi);
	OutColor3 = float4(InColor3.xy * sixthRecipPi, InColor3.zw * seventhRecipPi);
	*/
}

void FilterOSMPixelMain(
	in float2 TexCoord : TEXCOORD0,
	out float4 OutColor0 : COLOR0,
	out float4 OutColor1 : COLOR1,
	out float4 OutColor2 : COLOR2,
	out float4 OutColor3 : COLOR3
	)
{
	float FilterRadius = 4;
	float FilterStepSize = 2;
	float FilterNumTaps = (2*FilterRadius+1);

	OutColor0 = 0;
	OutColor1 = 0;
	
	/*
	5 coeffs only...
	OutColor2 = 0;
	OutColor3 = 0;
	*/

	UNROLL
	for (float r = -FilterRadius; r <= FilterRadius; ++r) {
	    float2 uv = TexelSize * FilterStepSize * r + TexCoord;
	    OutColor0 += tex2D( ShadowOSMTexture0, uv );
	    OutColor1 += tex2D( ShadowOSMTexture1, uv );
	    
		/*
		5 coeffs only...
	    OutColor2 += tex2D( ShadowOSMTexture2, uv );
	    OutColor3 += tex2D( ShadowOSMTexture3, uv );
	    */
	}

	OutColor0 /= FilterNumTaps;
	OutColor1 /= FilterNumTaps;
	
	/*
	5 coeffs only...
	OutColor2 /= FilterNumTaps;
	OutColor3 /= FilterNumTaps;
	*/
}
