/*=============================================================================
	ShadowProjectionPixelShader.usf: Pixel shader for projecting a shadow depth buffer onto the scene.
	Copyright 1998-2008 Epic Games, Inc. All Rights Reserved.
=============================================================================*/

#include "Common.usf"
#include "ShadowProjectionCommon.usf"

float4x4 ScreenToShadowMatrix;

/**
* Entry point for uniform manual PCF that supports lights using normal shadows.
*/
void Main(
	in float4 ScreenPosition : TEXCOORD0,
// NVCHANGE_BEGIN: Stereo fixes
#if NV_STEREO_FIXES
	in float2 vPos : VPOS,
#endif // NV_STEREO_FIXES
// NVCHANGE_END: Stereo fixes
	out float4 OutColor : COLOR0
	)
{
// NVCHANGE_BEGIN: Stereo fixes
#if NV_STEREO_FIXES
	float4 TrueScreenPosition = VPosToClip(vPos);
#else // NV_STEREO_FIXES
	float4 TrueScreenPosition = ScreenPosition;
#endif // NV_STEREO_FIXES
	half SceneW = PreviousDepth(TrueScreenPosition);

	float4 ShadowPosition = MulMatrix(ScreenToShadowMatrix,float4(Unstereo(TrueScreenPosition.xy/TrueScreenPosition.w,SceneW) * SceneW,SceneW,1));
// NVCHANGE_END: Stereo fixes

	ShadowPosition.xy /= ShadowPosition.w;
	ShadowPosition.z = min(ShadowPosition.z,0.999);

	half Shadow = ManualPCF(ShadowPosition);

	// RETURN_COLOR not needed unless writing to SceneColor;
	OutColor = Square(Shadow);
}


/**
* Entry point for uniform hardware PCF that supports lights using normal shadows.
*/
void HardwarePCFMain(
	in float4 ScreenPosition : TEXCOORD0,
// NVCHANGE_BEGIN: Stereo fixes
#if NV_STEREO_FIXES
	in float2 vPos : VPOS,
#endif // NV_STEREO_FIXES
// NVCHANGE_END: Stereo fixes
	out float4 OutColor : COLOR0
	)
{
// NVCHANGE_BEGIN: Stereo fixes
#if NV_STEREO_FIXES
	float4 TrueScreenPosition = VPosToClip(vPos);
#else // NV_STEREO_FIXES
	float4 TrueScreenPosition = ScreenPosition;
#endif // NV_STEREO_FIXES
	half SceneW = PreviousDepth(TrueScreenPosition);

	float4 ShadowPosition = MulMatrix(ScreenToShadowMatrix,float4(Unstereo(TrueScreenPosition.xy/TrueScreenPosition.w,SceneW) * SceneW,SceneW,1));
// NVCHANGE_END: Stereo fixes

	ShadowPosition.xy /= ShadowPosition.w;
	ShadowPosition.z = min(ShadowPosition.z,0.999);

	half Shadow = HardwarePCF(ShadowPosition);
	
	// RETURN_COLOR not needed unless writing to SceneColor;
	OutColor = Square(Shadow);
}


/**
* Entry point for uniform Fetch4 PCF that supports lights using normal shadows.
*/
void Fetch4Main(
	in float4 ScreenPosition : TEXCOORD0,
// NVCHANGE_BEGIN: Stereo fixes
#if NV_STEREO_FIXES
	in float2 vPos : VPOS,
#endif // NV_STEREO_FIXES
// NVCHANGE_END: Stereo fixes
	out float4 OutColor : COLOR0
	)
{
// NVCHANGE_BEGIN: Stereo fixes
#if NV_STEREO_FIXES
	float4 TrueScreenPosition = VPosToClip(vPos);
#else // NV_STEREO_FIXES
	float4 TrueScreenPosition = ScreenPosition;
#endif // NV_STEREO_FIXES
	half SceneW = PreviousDepth(TrueScreenPosition);

	float4 ShadowPosition = MulMatrix(ScreenToShadowMatrix,float4(Unstereo(TrueScreenPosition.xy/TrueScreenPosition.w,SceneW) * SceneW,SceneW,1));
// NVCHANGE_END: Stereo fixes

	ShadowPosition.xy /= ShadowPosition.w;
	ShadowPosition.z = min(ShadowPosition.z,0.999);

	half Shadow = Fetch4PCF(ShadowPosition);
	
	// RETURN_COLOR not needed unless writing to SceneColor;
	OutColor = Square(Shadow);
}