/*=============================================================================
	ShadowOpacityPixelShader.usf: Pixel shader for writing shadow opacity.
	Copyright 2009 NVIDIA Corporation, All Rights Reserved.
=============================================================================*/

// This to prevent DepthBiasedAlpha() and DepthBiasedBlend() from malfunctioning
#define SKIP_SCREENSPACE_TEXTURE_LOOKUPS 1

#include "Common.usf"
#include "Material.usf"
#include "VertexFactory.usf"
#include "ShadowOpacityCommon.usf"

void Main( 
	FVertexFactoryInterpolants FactoryInterpolants,
	float ShadowDepth : TEXCOORD4,
	out float4 OutColor0 : COLOR0,
	out float4 OutColor1 : COLOR1,
	out float4 OutColor2 : COLOR2,
	out float4 OutColor3 : COLOR3
	)
{
	// Evaluate the mask for masked materials
	FMaterialParameters MaterialParameters = GetMaterialParameters(FactoryInterpolants);
	// Note: Using default values for camera vector and screen position to reduce interpolator cost.
	// If the mask depends on either of these it will be subtly wrong.
	CalcMaterialParameters(MaterialParameters, 1, float3(0,0,1), float4(0,0,0,1));

	float Opacity = saturate(GetMaterialOpacity(MaterialParameters));
	Opacity *= opacityMultiplier;
	
	float lnTransmittance = -log(1 - Opacity);
	
	// Layer count - we use this to approximate the geometric-mean-transmissivity, and from there the color tint
	OutColor0.r = 1.f;
	
	// DC component
	OutColor0.g = lnTransmittance;
	
	// Remaining outputs require sin/cos
	float2 cs1;
	sincos(M_TWO_PI * ShadowDepth, cs1.y, cs1.x);
	OutColor0.ba = lnTransmittance * cs1;
	
	float2 csn = float2(cs1.x*cs1.x-cs1.y*cs1.y, 2.f*cs1.y*cs1.x);
	OutColor1.rg = lnTransmittance * csn;
	
	csn = float2(csn.x*cs1.x-csn.y*cs1.y, csn.y*cs1.x+csn.x*cs1.y);
	OutColor1.ba = lnTransmittance * csn;
	
	/*
	5 coeffs only...
	csn = float2(csn.x*cs1.x-csn.y*cs1.y, csn.y*cs1.x+csn.x*cs1.y);
	OutColor2.rg = lnTransmittance * csn;
	
	csn = float2(csn.x*cs1.x-csn.y*cs1.y, csn.y*cs1.x+csn.x*cs1.y);
	OutColor2.ba = lnTransmittance * csn;
	
	csn = float2(csn.x*cs1.x-csn.y*cs1.y, csn.y*cs1.x+csn.x*cs1.y);
	OutColor3.rg = lnTransmittance * csn;
	
	csn = float2(csn.x*cs1.x-csn.y*cs1.y, csn.y*cs1.x+csn.x*cs1.y);
	OutColor3.ba = lnTransmittance * csn;
	*/
}

