/*=============================================================================
	StereoExemplarPixelShader.usf: Pixel shader for writing stereo exemplars
	Copyright 2009 NVIDIA Corporation, All Rights Reserved.
=============================================================================*/

#include "Common.usf"

void Main(
	in float4 ScreenPosition : TEXCOORD0,
	in float2 vPos : VPOS,
	out float4 OutColor : COLOR0
	)
{
	float4 TrueScreenPosition = VPosToClip(vPos);

	// Write out z and the stereo delta
	OutColor.r = TrueScreenPosition.x - (ScreenPosition.x/ScreenPosition.w);
	OutColor.g = ScreenPosition.w;
	OutColor.b = 0.f;
	OutColor.a = 1.f;
}
