/*=============================================================================
	StereoExemplarVertexShader.usf: Vertex shader for writing stereo exemplars
	Copyright 2009 NVIDIA Corporation, All Rights Reserved.
=============================================================================*/

#include "Common.usf"

float4x4 ProjectionMatrix;

void Main(
	in float4 InPosition : POSITION,
	out float4 OutScreenPosition : TEXCOORD0,
	out float4 OutPosition : POSITION
	)
{
	OutPosition = OutScreenPosition = MulMatrix(ProjectionMatrix,InPosition);
}
