/**
 * Class: GUDData_LocustBoomerB
 * Gears Unscripted Dialog data for a single character.
 * Copyright 1998-2008 Epic Games, Inc. All Rights Reserved.
*/
class GUDData_LocustBoomerB extends GUDBank
	notplaceable
	abstract;

/** **** This file autogenerated by GUDS.xls.  Do not edit by hand. **** **/
defaultproperties
{
	GUDLines(0)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_ForHorde_Loud01Cue')
	GUDLines(1)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_ForHorde_Loud02Cue')
	GUDLines(2)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_ForQueen_Loud01Cue')
	GUDLines(3)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_ForQueen_Medium01Cue')
	GUDLines(4)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_DieGroundwalker_Loud01Cue',bAlwaysLoad=1)
	GUDLines(5)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_DieGroundwalker_Loud02Cue')
	GUDLines(6)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_DieHominid_Loud01Cue')
	GUDLines(7)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_DieHominid_Loud02Cue')
	GUDActions(GUDAction_EnteredCombat_I)=(LineIndices=(0,1,2,3,4,5,6,7))

	GUDLines(8)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.LosingSightOfEnemy.Boomer2Chatter_Blind_Medium01Cue',bAlwaysLoad=1)
	GUDLines(9)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.LosingSightOfEnemy.Boomer2Chatter_Gone_Loud01Cue')
	GUDLines(10)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.LosingSightOfEnemy.Boomer2Chatter_ItGone_Medium01Cue')
	GUDLines(11)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.LosingSightOfEnemy.Boomer2Chatter_Lost_Medium01Cue')
	GUDLines(12)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.LosingSightOfEnemy.Boomer2Chatter_LostGroundwalker_Medium01Cue')
	GUDLines(13)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.LosingSightOfEnemy.Boomer2Chatter_LostIt_Medium01Cue')
	GUDActions(GUDAction_LostTarget_I)=(LineIndices=(8,9,10,11,12,13))

	GUDLines(14)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.GainingSightOfEnemy.Boomer2Chatter_Found_Medium01Cue',bAlwaysLoad=1,Addressee=GUDRole_Recipient)
	GUDLines(15)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.GainingSightOfEnemy.Boomer2Chatter_FoundGroundwalker_Loud01Cue',Addressee=GUDRole_Recipient)
	GUDLines(16)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.GainingSightOfEnemy.Boomer2Chatter_FoundGroundwalker_Medium01Cue',Addressee=GUDRole_Recipient)
	GUDLines(17)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.GainingSightOfEnemy.Boomer2Chatter_SeeGroundwalker_Loud01Cue',Addressee=GUDRole_Recipient)
	GUDLines(18)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.GainingSightOfEnemy.Boomer2Chatter_SeeGroundwalker_Loud02Cue',Addressee=GUDRole_Recipient)
	GUDLines(19)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.GainingSightOfEnemy.Boomer2Chatter_Seen_Medium01Cue',Addressee=GUDRole_Recipient)
	GUDActions(GUDAction_FoundTarget_I)=(LineIndices=(14,15,16,17,18,19))

	GUDLines(20)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Dead_Loud01Cue',bAlwaysLoad=1)
	GUDLines(21)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Medium07Cue')
	GUDLines(22)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Medium08Cue')
	GUDLines(23)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Medium09Cue')
	GUDLines(24)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Medium10Cue')
	GUDLines(25)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Die_Loud02Cue')
	GUDLines(26)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Die_Medium01Cue')
	GUDLines(27)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Die_Medium02Cue')
	GUDActions(GUDAction_KilledEnemyGeneric_I)=(LineIndices=(20,21,22,23,24,25,26,27))

	GUDLines(28)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Dead_Loud01Cue',bAlwaysLoad=1)
	GUDLines(29)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Medium07Cue')
	GUDLines(30)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Medium08Cue')
	GUDLines(31)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Medium09Cue')
	GUDLines(32)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Medium10Cue')
	GUDLines(33)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Bash_Loud01Cue')
	GUDLines(34)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Break_Loud01Cue')
	GUDLines(35)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Crush_Medium01Cue')
	GUDLines(36)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Pound_Loud01Cue')
	GUDActions(GUDAction_KilledEnemyMelee_I)=(LineIndices=(28,29,30,31,32,33,34,35,36))

	GUDLines(37)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Loud03Cue',bAlwaysLoad=1)
	GUDLines(38)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Medium01Cue')
	GUDLines(39)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Medium04Cue')
	GUDLines(40)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_DieGroundwalker_Loud01Cue')
	GUDLines(41)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_DieHominid_Loud01Cue')
	GUDActions(GUDAction_DamagedEnemyHeavy_I)=(LineIndices=(37,38,39,40,41))

	GUDLines(42)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.TakingDamage.Boomer2Chatter_FrustratedGrunt_Effort03Cue',bAlwaysLoad=1)
	GUDLines(43)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.TakingDamage.Boomer2Chatter_FrustratedGrunt_Effort01Cue')
	GUDLines(44)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.TakingDamage.Boomer2Chatter_FrustratedGrunt_Effort02Cue')
	GUDLines(45)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.TakingDamage.Boomer2Chatter_PainHit_Effor08Cue')
	GUDLines(46)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.TakingDamage.Boomer2Chatter_PainHit_Effor09Cue')
	GUDActions(GUDAction_DamagedEnemyHeavy_R)=(LineIndices=(42,43,44,45,46))

	GUDLines(47)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Medium03Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_TransToRetreatAI_EW)=(LineIndices=(47))

	GUDLines(48)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Attack04Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_TransToAdvanceAI_I)=(LineIndices=(48))

	GUDLines(49)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Charge_Loud01Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_TransToKamikazeAI_I)=(LineIndices=(49))

	GUDLines(50)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Pound_Loud01Cue',bAlwaysLoad=1)
	GUDLines(51)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Pound_Medium01Cue')
	GUDLines(52)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Crush_Medium01Cue')
	GUDLines(53)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Crush_Loud01Cue')
	GUDLines(54)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Bash_Medium01Cue')
	GUDLines(55)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Bash_Loud01Cue')
	GUDActions(GUDAction_TransToMeleeAI_I)=(LineIndices=(50,51,52,53,54,55))

	GUDLines(56)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Crush_Loud01Cue',bAlwaysLoad=1)
	GUDLines(57)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Mine_Loud01Cue')
	GUDLines(58)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Mine_Medium01Cue')
	GUDActions(GUDAction_TransToMeleeAI_EW)=(LineIndices=(56,57,58))

	GUDLines(59)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Grenade01Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_ThrowingSmokeGrenade_EW)=(LineIndices=(59))

	GUDLines(60)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Grenade03Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_ThrowingFragGrenade_EW)=(LineIndices=(60))

	GUDLines(61)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.TakingDamage.Boomer2Chatter_FrustratedGrunt_Effort02Cue',bAlwaysLoad=1)
	GUDLines(62)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.ExtraEfforts.Boomer2Chatter_OnFire_Short01Cue')
	GUDActions(GUDAction_Reloaded_I)=(LineIndices=(61,62))

	GUDLines(63)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_IHunger_Medium02Cue',bAlwaysLoad=1)
	GUDLines(64)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Hunger_Loud01Cue')
	GUDLines(65)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Hunger_Medium01Cue')
	GUDLines(66)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_VictoryRoar01Cue')
	GUDLines(67)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_VictoryRoar03Cue')
	GUDActions(GUDAction_CombatLull_EW)=(LineIndices=(63,64,65,66,67))

	GUDLines(68)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Burn_Medium01Cue',bAlwaysLoad=1)
	GUDLines(69)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Burn_Medium02Cue')
	GUDLines(70)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.WeaponOverheats.Boomer2Chatter_Hot_Medium01Cue')
	GUDLines(71)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Die_Medium01Cue')
	GUDLines(72)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.AttackingEnemy.Boomer2Chatter_Die_Medium02Cue')
	GUDActions(GUDAction_KilledEnemyFlamethrower_I)=(LineIndices=(68,69,70,71,72))

	GUDLines(73)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Skyfire01Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_MortarLaunched_EW)=(LineIndices=(73))

	GUDLines(74)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Grenade01Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_ThrowingInkGrenade_EW)=(LineIndices=(74))

	GUDLines(75)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.TakingDamage.Boomer2Chatter_FrustratedGrunt_Effort01Cue',bAlwaysLoad=1)
	GUDLines(76)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.TakingDamage.Boomer2Chatter_PainHit_Effor09Cue')
	GUDLines(77)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.TakingDamage.Boomer2Chatter_PainHit_Effor07Cue')
	GUDLines(78)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.TakingDamage.Boomer2Chatter_PainHit_Effor06Cue')
	GUDActions(GUDAction_StuckExplosiveToEnemy_R)=(LineIndices=(75,76,77,78))

	GUDLines(79)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Medium01Cue',bAlwaysLoad=1)
	GUDLines(80)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Medium03Cue')
	GUDLines(81)=(Audio=SoundCue'Locust_Boomer2_Chatter_Cue.KilledEnemy.Boomer2Chatter_Laugh_Medium04Cue')
	GUDActions(GUDAction_DBNOPawnCrawlingAway_EW)=(LineIndices=(79,80,81))

}
