/**
 * Class: GUDData_LocustBoomer
 * Gears Unscripted Dialog data for a single character.
 * Copyright 1998-2008 Epic Games, Inc. All Rights Reserved.
*/
class GUDData_LocustBoomer extends GUDBank
	notplaceable
	abstract;

/** **** This file autogenerated by GUDS.xls.  Do not edit by hand. **** **/
defaultproperties
{
	GUDLines(0)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_ForHorde_Loud01Cue',bAlwaysLoad=1)
	GUDLines(1)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_ForHorde_Loud02Cue')
	GUDLines(2)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_ForQueen_Loud02Cue')
	GUDLines(3)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_ForQueen_Loud01Cue')
	GUDLines(4)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Kill_Loud03Cue')
	GUDLines(5)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Destroy_Loud01Cue')
	GUDActions(GUDAction_EnteredCombat_I)=(LineIndices=(0,1,2,3,4,5))

	GUDLines(6)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.LosingSightOfEnemy.Boomer1Chatter_Blind_Loud01Cue')
	GUDLines(7)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.LosingSightOfEnemy.Boomer1Chatter_Blind_Loud03Cue')
	GUDLines(8)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.LosingSightOfEnemy.Boomer1Chatter_Blind_Loud04Cue',bAlwaysLoad=1)
	GUDLines(9)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.LosingSightOfEnemy.Boomer1Chatter_Gone_Loud01Cue')
	GUDLines(10)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.LosingSightOfEnemy.Boomer1Chatter_Gone_Loud03Cue')
	GUDLines(11)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.LosingSightOfEnemy.Boomer1Chatter_Gone_Loud04Cue')
	GUDLines(12)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.LosingSightOfEnemy.Boomer1Chatter_GroundwalkerGone_Loud01Cue')
	GUDLines(13)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.LosingSightOfEnemy.Boomer1Chatter_GroundwalkerGone_Loud02Cue')
	GUDLines(14)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.LosingSightOfEnemy.Boomer1Chatter_LostGroundwalker_Loud02Cue')
	GUDLines(15)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.LosingSightOfEnemy.Boomer1Chatter_LostGroundwalker_Loud03Cue')
	GUDActions(GUDAction_LostTarget_I)=(LineIndices=(6,7,8,9,10,11,12,13,14,15))

	GUDLines(16)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.GainingSightOfEnemy.Boomer1Chatter_Seen_Loud03Cue')
	GUDLines(17)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.GainingSightOfEnemy.Boomer1Chatter_Found_Loud01Cue',bAlwaysLoad=1)
	GUDLines(18)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.GainingSightOfEnemy.Boomer1Chatter_Found_Loud02Cue')
	GUDLines(19)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.GainingSightOfEnemy.Boomer1Chatter_Found_Loud03Cue')
	GUDLines(20)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.GainingSightOfEnemy.Boomer1Chatter_FoundGroundwalker_Loud01Cue')
	GUDLines(21)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.GainingSightOfEnemy.Boomer1Chatter_FoundGroundwalker_Loud02Cue')
	GUDLines(22)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.GainingSightOfEnemy.Boomer1Chatter_FoundGroundwalker_Loud03Cue')
	GUDLines(23)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.GainingSightOfEnemy.Boomer1Chatter_FoundGroundwalker_Loud04Cue')
	GUDLines(24)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.GainingSightOfEnemy.Boomer1Chatter_SeeGroundwalker_Loud01Cue')
	GUDLines(25)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.GainingSightOfEnemy.Boomer1Chatter_SeeGroundwalker_Loud02Cue')
	GUDLines(26)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.GainingSightOfEnemy.Boomer1Chatter_SeeGroundwalker_Medium01Cue')
	GUDLines(27)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.GainingSightOfEnemy.Boomer1Chatter_Seen_Loud01Cue')
	GUDLines(28)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.GainingSightOfEnemy.Boomer1Chatter_Seen_Loud02Cue')
	GUDActions(GUDAction_FoundTarget_I)=(LineIndices=(16,17,18,19,20,21,22,23,24,25,26,27,28))

	GUDLines(29)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.KilledEnemy.Boomer1Chatter_Dead_Medium02Cue',bAlwaysLoad=1)
	GUDLines(30)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.KilledEnemy.Boomer1Chatter_Dead_Medium01Cue')
	GUDLines(31)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.KilledEnemy.Boomer1Chatter_Dead_Medium03Cue')
	GUDLines(32)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.KilledEnemy.Boomer1Chatter_Laugh_Medium09Cue')
	GUDLines(33)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.KilledEnemy.Boomer1Chatter_Laugh_Medium01Cue')
	GUDLines(34)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Die_Loud01Cue')
	GUDLines(35)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Die_Loud03Cue')
	GUDActions(GUDAction_KilledEnemyGeneric_I)=(LineIndices=(29,30,31,32,33,34,35))

	GUDLines(36)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.KilledEnemy.Boomer1Chatter_Dead_Medium02Cue',bAlwaysLoad=1)
	GUDLines(37)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.KilledEnemy.Boomer1Chatter_Dead_Medium01Cue')
	GUDLines(38)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.KilledEnemy.Boomer1Chatter_Dead_Medium03Cue')
	GUDLines(39)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.KilledEnemy.Boomer1Chatter_Laugh_Medium09Cue')
	GUDLines(40)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.KilledEnemy.Boomer1Chatter_Laugh_Medium01Cue')
	GUDLines(41)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Break_Loud04Cue')
	GUDLines(42)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Crush_Loud03Cue')
	GUDActions(GUDAction_KilledEnemyMelee_I)=(LineIndices=(36,37,38,39,40,41,42))

	GUDLines(43)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Die_Loud03Cue',bAlwaysLoad=1)
	GUDLines(44)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.KilledEnemy.Boomer1Chatter_Laugh_Medium09Cue')
	GUDLines(45)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.KilledEnemy.Boomer1Chatter_Laugh_Medium09Cue')
	GUDLines(46)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_DieEnemy_Loud03Cue')
	GUDLines(47)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Kill_Loud03Cue')
	GUDActions(GUDAction_DamagedEnemyHeavy_I)=(LineIndices=(43,44,45,46,47))

	GUDLines(48)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.TakingDamage.Boomer1Chatter_Hurt_Medium01Cue',bAlwaysLoad=1)
	GUDLines(49)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.TakingDamage.Boomer1Chatter_No_Loud01Cue')
	GUDLines(50)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.TakingDamage.Boomer1Chatter_No_Loud02Cue')
	GUDLines(51)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.TakingDamage.Boomer1Chatter_No_Loud03Cue')
	GUDLines(52)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.TakingDamage.Boomer1Chatter_No_Medium01Cue')
	GUDLines(53)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.TakingDamage.Boomer1Chatter_No_Medium02Cue')
	GUDActions(GUDAction_DamagedEnemyHeavy_R)=(LineIndices=(48,49,50,51,52,53))

	GUDLines(54)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Gone03Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_TransToRetreatAI_EW)=(LineIndices=(54))

	GUDLines(55)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Attack02Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_TransToAdvanceAI_I)=(LineIndices=(55))

	GUDLines(56)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Charge02Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_TransToKamikazeAI_I)=(LineIndices=(56))

	GUDLines(57)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Pound_Loud06Cue',bAlwaysLoad=1)
	GUDLines(58)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Crush_Loud03Cue')
	GUDLines(59)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Bash_Loud03Cue')
	GUDLines(60)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Break_Loud03Cue')
	GUDActions(GUDAction_TransToMeleeAI_I)=(LineIndices=(57,58,59,60))

	GUDLines(61)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Dismember02Cue',bAlwaysLoad=1)
	GUDLines(62)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Come01Cue')
	GUDLines(63)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Come03Cue')
	GUDActions(GUDAction_TransToMeleeAI_EW)=(LineIndices=(61,62,63))

	GUDLines(64)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Grenade01Cue',bAlwaysLoad=1)
	GUDLines(65)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Grenade02Cue')
	GUDLines(66)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Grenade03Cue')
	GUDActions(GUDAction_ThrowingSmokeGrenade_EW)=(LineIndices=(64,65,66))

	GUDLines(67)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Grenade01Cue',bAlwaysLoad=1)
	GUDLines(68)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Grenade02Cue')
	GUDLines(69)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Grenade03Cue')
	GUDActions(GUDAction_ThrowingFragGrenade_EW)=(LineIndices=(67,68,69))

	GUDLines(70)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Frustration03Cue',bAlwaysLoad=1)
	GUDLines(71)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Frustration01Cue')
	GUDActions(GUDAction_Reloaded_I)=(LineIndices=(70,71))

	GUDLines(72)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Hunger_Loud04Cue',bAlwaysLoad=1)
	GUDLines(73)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_IHunger_Loud02Cue')
	GUDLines(74)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Destroy_Medium01Cue')
	GUDLines(75)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_ScreamCharging02Cue')
	GUDLines(76)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_VictoryRoar02Cue')
	GUDActions(GUDAction_CombatLull_EW)=(LineIndices=(72,73,74,75,76))

	GUDLines(77)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Burn_Loud01Cue',bAlwaysLoad=1)
	GUDLines(78)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Burn_Loud02Cue')
	GUDLines(79)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Burn_Loud03Cue')
	GUDLines(80)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Burn_Loud04Cue')
	GUDLines(81)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Flame_Loud04Cue')
	GUDLines(82)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.AttackingEnemy.Boomer1Chatter_Flame_Loud02Cue')
	GUDLines(83)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.WeaponOverheats.Boomer1Chatter_Burning_Medium01Cue')
	GUDLines(84)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.WeaponOverheats.Boomer1Chatter_Burning_Medium02Cue')
	GUDActions(GUDAction_KilledEnemyFlamethrower_I)=(LineIndices=(77,78,79,80,81,82,83,84))

	GUDLines(85)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Skyfire01Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_MortarLaunched_EW)=(LineIndices=(85))

	GUDLines(86)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Grenade02Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_ThrowingInkGrenade_EW)=(LineIndices=(86))

	GUDLines(87)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.TakingDamage.Boomer1Chatter_No_Medium01Cue',bAlwaysLoad=1)
	GUDLines(88)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.TakingDamage.Boomer1Chatter_Grunt_Effort13Cue')
	GUDLines(89)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.TakingDamage.Boomer1Chatter_Grunt_Effort03Cue')
	GUDLines(90)=(Audio=SoundCue'Locust_Boomer1_Chatter_Cue.TakingDamage.Boomer1Chatter_Grunt_Effort04Cue')
	GUDActions(GUDAction_StuckExplosiveToEnemy_R)=(LineIndices=(87,88,89,90))

	GUDLines(91)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_Pitiful03Cue',bAlwaysLoad=1)
	GUDLines(92)=(Audio=SoundCue'Locust_Boomer_Chatter_Cue.BoomerSingle.BoomerChatter_PityLaugh01Cue')
	GUDActions(GUDAction_DBNOPawnCrawlingAway_EW)=(LineIndices=(91,92))

}
