/**
 * Class: GUDData_LocustKantus
 * Gears Unscripted Dialog data for a single character.
 * Copyright 1998-2008 Epic Games, Inc. All Rights Reserved.
*/
class GUDData_LocustKantus extends GUDBank
	notplaceable
	abstract;

/** **** This file autogenerated by GUDS.xls.  Do not edit by hand. **** **/
defaultproperties
{
	GUDLines(0)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemiesSpotted.KantusChatter_Groundwalkers_Loud03Cue',bAlwaysLoad=1)
	GUDLines(1)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemiesSpotted.KantusChatter_Hostiles_Medium01Cue')
	GUDLines(2)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemiesSpotted.KantusChatter_Hostiles_Medium02Cue')
	GUDLines(3)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemiesSpotted.KantusChatter_Ominids_Loud02Cue')
	GUDLines(4)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemiesSpotted.KantusChatter_Sapiens_Medium02Cue')
	GUDActions(GUDAction_EnteredCombat_I)=(LineIndices=(0,1,2,3,4))

	GUDLines(5)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCalloutResponseCantSee.KantusChatter_Sightess_Medium01Cue',bAlwaysLoad=1)
	GUDLines(6)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCalloutResponseCantSee.KantusChatter_SightlineBlind_Medium01Cue')
	GUDActions(GUDAction_LostTarget_I)=(LineIndices=(5,6))

	GUDLines(7)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCalloutResponseCanSee.KantusChatter_Seen_Medium01Cue',bAlwaysLoad=1)
	GUDLines(8)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCalloutResponseCanSee.KantusChatter_Seen_Medium02Cue')
	GUDLines(9)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCalloutResponseCanSee.KantusChatter_Sighted_Loud01Cue')
	GUDLines(10)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCalloutResponseCanSee.KantusChatter_Sighted_Loud03Cue')
	GUDActions(GUDAction_FoundTarget_I)=(LineIndices=(7,8,9,10))

	GUDLines(11)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_Die_Medium01Cue',bAlwaysLoad=1)
	GUDLines(12)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.SuccessfullyActiveReload.KantusChatter_EvilLaugh05Cue')
	GUDLines(13)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.KilledEnemy.KantusChatter_Filth_Loud01Cue')
	GUDLines(14)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BecomingMeatShield.KantusChatter_KillYou02Cue')
	GUDLines(15)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.PickingUpWeaponsAndAmmo.KantusChatter_ShortChuckle04Cue')
	GUDLines(16)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_Succumb_Loud01Cue')
	GUDActions(GUDAction_KilledEnemyGeneric_I)=(LineIndices=(11,12,13,14,15,16))

	GUDLines(17)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.KilledEnemy.KantusChatter_Bleed_Medium01Cue',bAlwaysLoad=1)
	GUDLines(18)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_Suffer_Medium01Cue')
	GUDLines(19)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.SuccessfullyActiveReload.KantusChatter_EvilLaugh05Cue')
	GUDLines(20)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BecomingMeatShield.KantusChatter_KillYou01Cue')
	GUDActions(GUDAction_DamagedEnemyHeavy_I)=(LineIndices=(17,18,19,20))

	GUDLines(21)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.HitReactionsTakingDamage.KantusChatter_Pain_Loud02Cue',bAlwaysLoad=1)
	GUDLines(22)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.GivingOrdersToSquad.KantusChatter_Defend01Cue')
	GUDLines(23)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_BattleCry01Cue')
	GUDLines(24)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.HitReactionsTakingDamage.KantusChatter_Hurt_Loud02Cue')
	GUDActions(GUDAction_DamagedEnemyHeavy_R)=(LineIndices=(21,22,23,24))

	GUDLines(25)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.PickedUpFlamethrower.KantusChatter_Burn03Cue',bAlwaysLoad=1)
	GUDLines(26)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.KilledEnemyWithFlamethrower.KantusChatter_BurnGroundwalker01Cue')
	GUDLines(27)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.KilledEnemyWithFlamethrower.KantusChatter_BurnHuman01Cue')
	GUDLines(28)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.HitReactionsTakingDamage.KantusChatter_Skyfire01Cue')
	GUDActions(GUDAction_KilledEnemyHOD_I)=(LineIndices=(25,26,27,28))

	GUDLines(29)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_MovingBack01Cue',bAlwaysLoad=1)
	GUDLines(30)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_MovingBack02Cue')
	GUDLines(31)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_Retreating01Cue')
	GUDLines(32)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_Retreating02Cue')
	GUDActions(GUDAction_TransToRetreatAI_I)=(LineIndices=(29,30,31,32))

	GUDLines(33)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_Advancing01Cue',bAlwaysLoad=1)
	GUDLines(34)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_Advancing02Cue')
	GUDLines(35)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_Moving02Cue')
	GUDLines(36)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_Moving01Cue')
	GUDLines(37)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_Shifting01Cue')
	GUDLines(38)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_Shifting02Cue')
	GUDActions(GUDAction_TransToAdvanceAI_I)=(LineIndices=(33,34,35,36,37,38))

	GUDLines(39)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_ForTheQueen_Loud01Cue',bAlwaysLoad=1)
	GUDLines(40)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_ForTheHorde_Loud01Cue')
	GUDActions(GUDAction_TransToKamikazeAI_I)=(LineIndices=(39,40))

	GUDLines(41)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_Die_Scream01Cue',bAlwaysLoad=1)
	GUDLines(42)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_Die_Medium02Cue')
	GUDLines(43)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_Die_Medium01Cue')
	GUDActions(GUDAction_TransToMeleeAI_I)=(LineIndices=(41,42,43))

	GUDLines(44)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ThrowingGrenades.KantusChatter_ComingFrag01Cue',bAlwaysLoad=1)
	GUDLines(45)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ThrowingGrenades.KantusChatter_ComingFrag02Cue')
	GUDActions(GUDAction_ThrowingFragGrenade_EW)=(LineIndices=(44,45))

	GUDLines(46)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.HitReactionsTakingDamage.KantusChatter_ShotReaction04Cue',bAlwaysLoad=1)
	GUDLines(47)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ExtraEfforts.KantusEffort_SingleRoar16Cue')
	GUDActions(GUDAction_GenericWentDown_I)=(LineIndices=(46,47))

	GUDLines(48)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ExtraEfforts.KantusEffort_CagedAndProdded04Cue',bAlwaysLoad=1)
	GUDLines(49)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ExtraEfforts.KantusEffort_CagedAndProdded06Cue')
	GUDLines(50)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.TakingDamageFromTeammate.KantusChatter_PissedMonsterSound10Cue')
	GUDLines(51)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.TakingDamageFromTeammate.KantusChatter_PissedMonsterSound11Cue')
	GUDActions(GUDAction_GenericNeedsRevived_I)=(LineIndices=(48,49,50,51))

	GUDLines(52)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.RevivingAnotherPlayer.KantusChatter_Arise_Medium01Cue',bAlwaysLoad=1,Addressee=GUDRole_Recipient)
	GUDLines(53)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.RevivingAnotherPlayer.KantusChatter_Ascend_Medium01Cue',Addressee=GUDRole_Recipient)
	GUDLines(54)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.RevivingAnotherPlayer.KantusChatter_Recover_Medium01Cue',Addressee=GUDRole_Recipient)
	GUDLines(55)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.RevivingAnotherPlayer.KantusChatter_Return_Medium01Cue',Addressee=GUDRole_Recipient)
	GUDLines(56)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.RevivingAnotherPlayer.KantusChatter_ServeTheQueen_Medium03Cue',Addressee=GUDRole_Recipient)
	GUDActions(GUDAction_Revived_I)=(LineIndices=(52,53,54,55,56))

	GUDLines(57)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.RevivingAnotherPlayer.KantusChatter_Vengence_Medium03Cue',bAlwaysLoad=1,Addressee=GUDRole_Instigator)
	GUDLines(58)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.SuccessfullyActiveReload.KantusChatter_Yes01Cue',Addressee=GUDRole_Instigator)
	GUDLines(59)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_ForTheQueen_Medium03Cue',Addressee=GUDRole_Instigator)
	GUDActions(GUDAction_Revived_R)=(LineIndices=(57,58,59))

	GUDLines(60)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_DieGroundwalker_Medium01Cue',bAlwaysLoad=1)
	GUDLines(61)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_DieGroundwalker_Medium02Cue')
	GUDLines(62)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_DieHuman_Medium01Cue')
	GUDLines(63)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_DieHuman_Medium02Cue')
	GUDLines(64)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_DieSapien_Medium01Cue')
	GUDLines(65)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.AttackingEnemy.KantusChatter_DieSapien_Medium02Cue')
	GUDActions(GUDAction_Attack_I)=(LineIndices=(60,61,62,63,64,65))

	GUDLines(66)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_BattleCry04Cue',bAlwaysLoad=1)
	GUDLines(67)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.RevivingAnotherPlayer.KantusChatter_Chant03Cue')
	GUDLines(68)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_BattleCry13Cue')
	GUDLines(69)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_BattleCry12Cue')
	GUDLines(70)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.BattleStatus.KantusChatter_BattleCry17Cue')
	GUDActions(GUDAction_CombatLull_EW)=(LineIndices=(66,67,68,69,70))

	GUDLines(71)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_High_Loud01Cue',bAlwaysLoad=1)
	GUDLines(72)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_High_Medium01Cue')
	GUDActions(GUDAction_EnemyLocationCallout_Above)=(LineIndices=(71,72))

	GUDLines(73)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_Low_Loud01Cue',bAlwaysLoad=1)
	GUDLines(74)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_Low_Medium01Cue')
	GUDActions(GUDAction_EnemyLocationCallout_Below)=(LineIndices=(73,74))

	GUDLines(75)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_Right_Medium02Cue',bAlwaysLoad=1)
	GUDLines(76)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_Right_Medium03Cue')
	GUDActions(GUDAction_EnemyLocationCallout_Right)=(LineIndices=(75,76))

	GUDLines(77)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_Left_Loud01Cue',bAlwaysLoad=1)
	GUDLines(78)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_Left_Medium01Cue')
	GUDActions(GUDAction_EnemyLocationCallout_Left)=(LineIndices=(77,78))

	GUDLines(79)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_Ahead_Medium01Cue',bAlwaysLoad=1)
	GUDLines(80)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_Ahead_Loud01Cue')
	GUDActions(GUDAction_EnemyLocationCallout_Ahead)=(LineIndices=(79,80))

	GUDLines(81)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_Behind_Loud01Cue',bAlwaysLoad=1)
	GUDLines(82)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_Behind_Medium02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_Behind)=(LineIndices=(81,82))

	GUDLines(83)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_AtWindow_Medium01Cue',bAlwaysLoad=1)
	GUDLines(84)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_AtWindows_Medium01Cue')
	GUDLines(85)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_InWindow_Medium01Cue')
	GUDLines(86)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_InWindows_Medium01Cue')
	GUDActions(GUDAction_EnemyLocationCallout_InWindow)=(LineIndices=(83,84,85,86))

	GUDLines(87)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_AtDoor_Loud01Cue',bAlwaysLoad=1)
	GUDLines(88)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_AtDoor_Medium01Cue')
	GUDActions(GUDAction_EnemyLocationCallout_InDoorway)=(LineIndices=(87,88))

	GUDLines(89)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_AtCar_Medium01Cue',bAlwaysLoad=1)
	GUDLines(90)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_BehindCar_Medium01Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindCar)=(LineIndices=(89,90))

	GUDLines(91)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_AtTruck_Medium01Cue',bAlwaysLoad=1)
	GUDLines(92)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_BehindTruck_Medium02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindTruck)=(LineIndices=(91,92))

	GUDLines(93)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_OnTruck_Medium01Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_EnemyLocationCallout_OnTruck)=(LineIndices=(93))

	GUDLines(94)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_AtBarriers_Medium02Cue',bAlwaysLoad=1)
	GUDLines(95)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_BehindBarriers_Medium02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindBarrier)=(LineIndices=(94,95))

	GUDLines(96)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_BehindColumns_Loud01Cue',bAlwaysLoad=1)
	GUDLines(97)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_BehindColumns_Medium02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindColumn)=(LineIndices=(96,97))

	GUDLines(98)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_BehindBox_Medium02Cue',bAlwaysLoad=1)
	GUDLines(99)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_BehindBoxes_Medium01Cue')
	GUDLines(100)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_BehindCrate_Medium02Cue')
	GUDLines(101)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_BehindCrates_Loud02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindCrate)=(LineIndices=(98,99,100,101))

	GUDLines(102)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_BehindWall_Medium01Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_EnemyLocationCallout_BehindWall)=(LineIndices=(102))

	GUDLines(103)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_AtStatue_Medium01Cue',bAlwaysLoad=1)
	GUDLines(104)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_BehindStatue_Medium01Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindStatue)=(LineIndices=(103,104))

	GUDLines(105)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_AtSandbags_Loud01Cue',bAlwaysLoad=1)
	GUDLines(106)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_AtSandbags_Loud03Cue')
	GUDLines(107)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemyCallouts.KantusChatter_BehindSandbags_Medium01Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindSandbags)=(LineIndices=(105,106,107))

	GUDLines(108)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemiesSpotted.KantusChatter_Incoming_Scream01Cue',bAlwaysLoad=1)
	GUDLines(109)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.EnemiesSpotted.KantusChatter_Incoming_Loud01Cue')
	GUDLines(110)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.HitReactionsTakingDamage.KantusChatter_Skyfire02Cue')
	GUDLines(111)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.HitReactionsTakingDamage.KantusChatter_Skyfire01Cue')
	GUDActions(GUDAction_MortarLaunched_EW)=(LineIndices=(108,109,110,111))

	GUDLines(112)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ThrowingGrenades.KantusChatter_Ink01Cue',bAlwaysLoad=1)
	GUDLines(113)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ThrowingGrenades.KantusChatter_Ink02Cue')
	GUDLines(114)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ThrowingGrenades.KantusChatter_InkOut01Cue')
	GUDLines(115)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ThrowingGrenades.KantusChatter_InkOut02Cue')
	GUDActions(GUDAction_ThrowingInkGrenade_I)=(LineIndices=(112,113,114,115))

	GUDLines(116)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ThrowingGrenades.KantusChatter_ComingInk02Cue',bAlwaysLoad=1)
	GUDLines(117)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ThrowingGrenades.KantusChatter_ComingInk01Cue')
	GUDActions(GUDAction_ThrowingInkGrenade_EW)=(LineIndices=(116,117))

	GUDLines(118)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.TakingWoundedAsMeatshield.KantusChatter_MeatChunk01Cue',bAlwaysLoad=1)
	GUDLines(119)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.TakingWoundedAsMeatshield.KantusChatter_HumanChunk02Cue')
	GUDLines(120)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.TakingWoundedAsMeatshield.KantusChatter_HumanChunk01Cue')
	GUDLines(121)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.PickingUpWeaponsAndAmmo.KantusChatter_ShortChuckle04Cue')
	GUDLines(122)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.TakingWoundedAsMeatshield.KantusChatter_SuccessLaugh03Cue')
	GUDLines(123)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.TakingWoundedAsMeatshield.KantusChatter_SuccessLaugh01Cue')
	GUDLines(124)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.TakingWoundedAsMeatshield.KantusChatter_SuccessLaugh02Cue')
	GUDActions(GUDAction_StuckExplosiveToEnemy_I)=(LineIndices=(118,119,120,121,122,123,124))

	GUDLines(125)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ShortCommentBeforeBlowingUp.KantusChatter_FrustratedGrunt01Cue',bAlwaysLoad=1)
	GUDLines(126)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ShortCommentBeforeBlowingUp.KantusChatter_FrustratedGrunt02Cue')
	GUDLines(127)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ShortCommentBeforeBlowingUp.KantusChatter_FrustratedGrunt03Cue')
	GUDLines(128)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ShortCommentBeforeBlowingUp.KantusChatter_MyQueen01Cue')
	GUDLines(129)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ShortCommentBeforeBlowingUp.KantusChatter_MyQueen03Cue')
	GUDLines(130)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ShortCommentBeforeBlowingUp.KantusChatter_No05Cue')
	GUDLines(131)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.ShortCommentBeforeBlowingUp.KantusChatter_OhNo02Cue')
	GUDActions(GUDAction_StuckExplosiveToEnemy_R)=(LineIndices=(125,126,127,128,129,130,131))

	GUDLines(132)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.WatchingWoundedCrawlAway.KantusChatter_CrawlMeat01Cue',bAlwaysLoad=1,Addressee=GUDRole_Instigator)
	GUDLines(133)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.WatchingWoundedCrawlAway.KantusChatter_CrawlMeat02Cue',Addressee=GUDRole_Instigator)
	GUDLines(134)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.WatchingWoundedCrawlAway.KantusChatter_GrovelMeat01Cue',Addressee=GUDRole_Instigator)
	GUDLines(135)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.WatchingWoundedCrawlAway.KantusChatter_GrovelMeat02Cue',Addressee=GUDRole_Instigator)
	GUDLines(136)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.WatchingWoundedCrawlAway.KantusChatter_BegGroundfeeder02Cue',Addressee=GUDRole_Instigator)
	GUDLines(137)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.WatchingWoundedCrawlAway.KantusChatter_BegGroundwalker01Cue',Addressee=GUDRole_Instigator)
	GUDLines(138)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.WatchingWoundedCrawlAway.KantusChatter_BegGroundwalker02Cue',Addressee=GUDRole_Instigator)
	GUDLines(139)=(Audio=SoundCue'Locust_Kantus_Chatter_Cue.WatchingWoundedCrawlAway.KantusChatter_BegHuman01Cue',Addressee=GUDRole_Instigator)
	GUDActions(GUDAction_DBNOPawnCrawlingAway_EW)=(LineIndices=(132,133,134,135,136,137,138,139))

}
