/**
 * Class: GUDData_LocustDroneMP
 * Gears Unscripted Dialog data for a single character.
 * Copyright 1998-2008 Epic Games, Inc. All Rights Reserved.
*/
class GUDData_LocustDroneMP extends GUDBank
	notplaceable
	abstract;

/** **** This file autogenerated by GUDS.xls.  Do not edit by hand. **** **/
defaultproperties
{
	GUDLines(0)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Meat01Cue',bAlwaysLoad=1)
	GUDLines(1)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterFilth01Cue')
	GUDLines(2)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Otiose02Cue')
	GUDLines(3)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterDie01Cue')
	GUDLines(4)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_AngryGrowl04Cue')
	GUDActions(GUDAction_KilledEnemyGeneric_I)=(LineIndices=(0,1,2,3,4))

	GUDLines(5)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Meat03Cue',bAlwaysLoad=1)
	GUDLines(6)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_SweetBlood01Cue')
	GUDLines(7)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Laugh01Cue')
	GUDLines(8)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_FeedGround03Cue')
	GUDLines(9)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingWoundedAsMeatshield.LocustAChatter_EvilChuckleOfSuccess01Cue')
	GUDLines(10)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingWoundedAsMeatshield.LocustAChatter_EvilChuckleOfSuccess02Cue')
	GUDLines(11)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingWoundedAsMeatshield.LocustAChatter_EvilChuckleOfSuccess03Cue')
	GUDActions(GUDAction_KilledEnemyChainsaw_I)=(LineIndices=(5,6,7,8,9,10,11))

	GUDLines(12)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_UglyOoman02Cue',bAlwaysLoad=1)
	GUDLines(13)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Growl01Cue')
	GUDLines(14)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Pathetic01Cue')
	GUDLines(15)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Inferior01Cue')
	GUDLines(16)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingWoundedAsMeatshield.LocustAChatter_EvilChuckleOfSuccess01Cue')
	GUDLines(17)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingWoundedAsMeatshield.LocustAChatter_EvilChuckleOfSuccess02Cue')
	GUDLines(18)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingWoundedAsMeatshield.LocustAChatter_EvilChuckleOfSuccess03Cue')
	GUDActions(GUDAction_KilledEnemyHeadShot_I)=(LineIndices=(12,13,14,15,16,17,18))

	GUDLines(19)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_SoWeak02Cue',bAlwaysLoad=1)
	GUDLines(20)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterDieOoman04Cue')
	GUDLines(21)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterWeak03Cue')
	GUDLines(22)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterCrush02Cue')
	GUDActions(GUDAction_KilledEnemyMelee_I)=(LineIndices=(19,20,21,22))

	GUDLines(23)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Puny03Cue',bAlwaysLoad=1)
	GUDLines(24)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_EatGround01Cue')
	GUDLines(25)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_YouWorm02Cue')
	GUDLines(26)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterSubducted02Cue')
	GUDActions(GUDAction_KilledEnemyCurbstomp_I)=(LineIndices=(23,24,25,26))

	GUDLines(27)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterPain02Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_DamagedEnemyHeavy_R)=(LineIndices=(27))

	GUDLines(28)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterDownMove02Cue',bAlwaysLoad=1)
	GUDLines(29)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterMove01Cue')
	GUDLines(30)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAGaveDamageToTeammate.LocustAChatter_Go02Cue')
	GUDLines(31)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAGaveDamageToTeammate.LocustAChatter_Go01Cue')
	GUDLines(32)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAGaveDamageToTeammate.LocustAChatter_Fight01Cue')
	GUDLines(33)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAGaveDamageToTeammate.LocustAChatter_Fight02Cue')
	GUDActions(GUDAction_DamageTeammate_I)=(LineIndices=(28,29,30,31,32,33))

	GUDLines(34)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Cease02Cue',bAlwaysLoad=1)
	GUDLines(35)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingDamageFromTeammate.LocustAChatter_KillOomans01Cue')
	GUDLines(36)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingDamageFromTeammate.LocustAChatter_KillOomans02Cue')
	GUDLines(37)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingDamageFromTeammate.LocustAChatter_ShootOomans01Cue')
	GUDLines(38)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingDamageFromTeammate.LocustAChatter_ShootOomans02Cue')
	GUDActions(GUDAction_DamageTeammate_R)=(LineIndices=(34,35,36,37,38))

	GUDLines(39)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_SmokeOut01Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_ThrowingSmokeGrenade_I)=(LineIndices=(39))

	GUDLines(40)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Smoke02Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_ThrowingSmokeGrenade_EW)=(LineIndices=(40))

	GUDLines(41)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_FragOut01Cue',bAlwaysLoad=1)
	GUDLines(42)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Frag02Cue')
	GUDActions(GUDAction_ThrowingFragGrenade_I)=(LineIndices=(41,42))

	GUDLines(43)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterGrenade02Cue',bAlwaysLoad=1)
	GUDLines(44)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Frag04Cue')
	GUDActions(GUDAction_ThrowingFragGrenade_EW)=(LineIndices=(43,44))

	GUDLines(45)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_AngryGrowl01Cue',bAlwaysLoad=1)
	GUDLines(46)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_AngryGrowl02Cue')
	GUDLines(47)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_AngryGrowl03Cue')
	GUDLines(48)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterBroken01Cue')
	GUDActions(GUDAction_FailedActiveReload_I)=(LineIndices=(45,46,47,48))

	GUDLines(49)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_AReload_Yes02Cue',bAlwaysLoad=1)
	GUDLines(50)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterKill02Cue')
	GUDLines(51)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterLaugh01Cue')
	GUDActions(GUDAction_SucceededActiveReload_I)=(LineIndices=(49,50,51))

	GUDLines(52)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Mine01Cue',bAlwaysLoad=1)
	GUDLines(53)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Taken02Cue')
	GUDLines(54)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_More01Cue')
	GUDLines(55)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterMine03Cue')
	GUDLines(56)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAPickingUpWeaponsAmmo.DroneAChatter_Seized01Cue')
	GUDActions(GUDAction_PickedUpAmmo_I)=(LineIndices=(52,53,54,55,56))

	GUDLines(57)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Mine01Cue',bAlwaysLoad=1)
	GUDLines(58)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_GotIt02Cue')
	GUDLines(59)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_PickupGrowl02Cue')
	GUDLines(60)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterMine02Cue')
	GUDLines(61)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAPickingUpWeaponsAmmo.DroneAChatter_Seized05Cue')
	GUDActions(GUDAction_PickedUpNewWeapon_I)=(LineIndices=(57,58,59,60,61))

	GUDLines(62)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Mine01Cue',bAlwaysLoad=1)
	GUDLines(63)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterMine01Cue')
	GUDLines(64)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAPickingUpWeaponsAmmo.DroneAChatter_Seized06Cue')
	GUDActions(GUDAction_PickedUpGrenades_I)=(LineIndices=(62,63,64))

	GUDLines(65)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_NoAmmo02Cue',bAlwaysLoad=1)
	GUDLines(66)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_NeedAmmo01Cue')
	GUDLines(67)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_NoFire01Cue')
	GUDLines(68)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_NeedFire03Cue')
	GUDActions(GUDAction_NeedAmmo_I)=(LineIndices=(65,66,67,68))

	GUDLines(69)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.LocustBChatterNone02Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_NeedAmmoGrenade_I)=(LineIndices=(69))

	GUDLines(70)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKnockedDownButNotOut.LocustAChatter_Down_Loud01Cue',bAlwaysLoad=1)
	GUDLines(71)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKnockedDownButNotOut.LocustAChatter_Down_Loud02Cue')
	GUDLines(72)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKnockedDownButNotOut.LocustAChatter_Down_Scream01Cue')
	GUDLines(73)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKnockedDownButNotOut.LocustAChatter_Down_Scream02Cue')
	GUDLines(74)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterDown01Cue')
	GUDActions(GUDAction_GenericWentDown_I)=(LineIndices=(70,71,72,73,74))

	GUDLines(75)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKnockedDownButNotOut.LocustAChatter_RestoreMe01_Loud01Cue',bAlwaysLoad=1)
	GUDLines(76)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKnockedDownButNotOut.LocustAChatter_RestoreMe01_Loud02Cue')
	GUDLines(77)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKnockedDownButNotOut.LocustAChatter_RestoreMe01_Scream01Cue')
	GUDLines(78)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKnockedDownButNotOut.LocustAChatter_RestoreMe01_Scream02Cue')
	GUDLines(79)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKnockedDownButNotOut.LocustAChatter_ReviveMe_Loud01Cue')
	GUDLines(80)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKnockedDownButNotOut.LocustAChatter_ReviveMe_Loud02Cue')
	GUDLines(81)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKnockedDownButNotOut.LocustAChatter_ReviveMe_Scream01Cue')
	GUDLines(82)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKnockedDownButNotOut.LocustAChatter_ReviveMe_Scream02Cue')
	GUDActions(GUDAction_GenericNeedsRevived_I)=(LineIndices=(75,76,77,78,79,80,81,82))

	GUDLines(83)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Attack01Cue',bAlwaysLoad=1,Addressee=GUDRole_Recipient)
	GUDLines(84)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Rise02Cue',Addressee=GUDRole_Recipient)
	GUDLines(85)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Stand03Cue',Addressee=GUDRole_Recipient)
	GUDLines(86)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Fight04Cue',Addressee=GUDRole_Recipient)
	GUDActions(GUDAction_Revived_I)=(LineIndices=(83,84,85,86))

	GUDLines(87)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_AReload_Yes01Cue',bAlwaysLoad=1)
	GUDLines(88)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_ForTheQueen03Cue')
	GUDLines(89)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Vengence03Cue')
	GUDLines(90)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Revenge03Cue')
	GUDActions(GUDAction_Revived_R)=(LineIndices=(87,88,89,90))

	GUDLines(91)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterPrimalScream03Cue',bAlwaysLoad=1)
	GUDLines(92)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneASingle.LocustAChatterGroundwalkers02Cue')
	GUDLines(93)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Grunts01Cue')
	GUDActions(GUDAction_CombatLull_EW)=(CombatOnlyLineIndices=(91,92,93))

	GUDLines(94)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_ForTheQueen06Cue',bAlwaysLoad=1)
	GUDLines(95)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Fight04Cue',bAlwaysLoad=1)
	GUDLines(96)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Destroy02Cue',bAlwaysLoad=1)
	GUDLines(97)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneBSingle.DroneChatter_Attack01Cue',bAlwaysLoad=1)
	GUDActions(GUDAction_VersusRoundBegunLocust_EW)=(LineIndices=(94,95,96,97))

	GUDLines(98)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_Above_Scream01Cue',bAlwaysLoad=1)
	GUDLines(99)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_Above_Scream02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_Above)=(LineIndices=(98,99))

	GUDLines(100)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_Below_Scream01Cue',bAlwaysLoad=1)
	GUDLines(101)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_Below_Scream02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_Below)=(LineIndices=(100,101))

	GUDLines(102)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_Right_Scream01Cue',bAlwaysLoad=1)
	GUDLines(103)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_Right_Scream02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_Right)=(LineIndices=(102,103))

	GUDLines(104)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_Left_Scream02Cue',bAlwaysLoad=1)
	GUDLines(105)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_Left_Scream01Cue')
	GUDActions(GUDAction_EnemyLocationCallout_Left)=(LineIndices=(104,105))

	GUDLines(106)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_Ahead_Scream01Cue',bAlwaysLoad=1)
	GUDLines(107)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_Ahead_Scream02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_Ahead)=(LineIndices=(106,107))

	GUDLines(108)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_Behind_Scream01Cue',bAlwaysLoad=1)
	GUDLines(109)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_Behind_Scream02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_Behind)=(LineIndices=(108,109))

	GUDLines(110)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_AtWindow_Scream02Cue',bAlwaysLoad=1)
	GUDLines(111)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_AtWindows_Scream02Cue')
	GUDLines(112)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_InWindow_Scream02Cue')
	GUDLines(113)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_InWindows_Scream02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_InWindow)=(LineIndices=(110,111,112,113))

	GUDLines(114)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_AtDoor_Scream01Cue',bAlwaysLoad=1)
	GUDLines(115)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_AtDoor_Scream02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_InDoorway)=(LineIndices=(114,115))

	GUDLines(116)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_AtCar_Scream02Cue',bAlwaysLoad=1)
	GUDLines(117)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_BehindCar_Scream02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindCar)=(LineIndices=(116,117))

	GUDLines(118)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_AtTruck_Scream02Cue',bAlwaysLoad=1)
	GUDLines(119)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_BehindTruck_Scream02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindTruck)=(LineIndices=(118,119))

	GUDLines(120)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_OnTruck_Scream01Cue',bAlwaysLoad=1)
	GUDLines(121)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_OnTruck_Scream02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_OnTruck)=(LineIndices=(120,121))

	GUDLines(122)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_AtBarriers_Scream02Cue',bAlwaysLoad=1)
	GUDLines(123)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_BehindBarriers_Scream02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindBarrier)=(LineIndices=(122,123))

	GUDLines(124)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_BehindColumns_Scream01Cue',bAlwaysLoad=1)
	GUDLines(125)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_BehindColumns_Scream02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindColumn)=(LineIndices=(124,125))

	GUDLines(126)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_BehindBox_Scream02Cue',bAlwaysLoad=1)
	GUDLines(127)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_BehindBoxes_Scream02Cue')
	GUDLines(128)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_BehindCrate_Scream02Cue')
	GUDLines(129)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_BehindCrates_Scream02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindCrate)=(LineIndices=(126,127,128,129))

	GUDLines(130)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_BehindWall_Loud01Cue',bAlwaysLoad=1)
	GUDLines(131)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_BehindWall_Scream02Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindWall)=(LineIndices=(130,131))

	GUDLines(132)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_BehindStatue_Scream01Cue',bAlwaysLoad=1)
	GUDLines(133)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_AtStatue_Scream01Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindStatue)=(LineIndices=(132,133))

	GUDLines(134)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_AtSandbags_Scream01Cue',bAlwaysLoad=1)
	GUDLines(135)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemyCallouts.LocustAChatter_BehindSandbags_Scream01Cue')
	GUDActions(GUDAction_EnemyLocationCallout_BehindSandbags)=(LineIndices=(134,135))

	GUDLines(136)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingWoundedAsMeatshield.LocustAChatter_MeatShield01Cue',bAlwaysLoad=1,Addressee=GUDRole_Recipient)
	GUDLines(137)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingWoundedAsMeatshield.LocustAChatter_MeatShield02Cue',Addressee=GUDRole_Recipient)
	GUDLines(138)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingWoundedAsMeatshield.LocustAChatter_Protected02Cue',Addressee=GUDRole_Recipient)
	GUDLines(139)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingWoundedAsMeatshield.LocustAChatter_Protected01Cue',Addressee=GUDRole_Recipient)
	GUDLines(140)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingWoundedAsMeatshield.LocustAChatter_OomanChunk02Cue',Addressee=GUDRole_Recipient)
	GUDLines(141)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingWoundedAsMeatshield.LocustAChatter_OomanChunk01Cue',Addressee=GUDRole_Recipient)
	GUDActions(GUDAction_PickedUpMeatShield_I)=(LineIndices=(136,137,138,139,140,141))

	GUDLines(142)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneABecomingMeatshield.LocustAChatter_FreeMe02Cue',bAlwaysLoad=1,Addressee=GUDRole_Instigator)
	GUDLines(143)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneABecomingMeatshield.LocustAChatter_FreeMe03Cue',Addressee=GUDRole_Instigator)
	GUDLines(144)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneABecomingMeatshield.LocustAChatter_FrustratedRage03Cue',Addressee=GUDRole_Instigator)
	GUDLines(145)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneABecomingMeatshield.LocustAChatter_KillYou01Cue',Addressee=GUDRole_Instigator)
	GUDLines(146)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneABecomingMeatshield.LocustAChatter_KillYou02Cue',Addressee=GUDRole_Instigator)
	GUDActions(GUDAction_PickedUpMeatShield_R)=(LineIndices=(142,143,144,145,146))

	GUDLines(147)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKilledEnemyWithFlamethrower.LocustAChatter_BurnGroundwalker02Cue',bAlwaysLoad=1,Addressee=GUDRole_Recipient)
	GUDLines(148)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKilledEnemyWithFlamethrower.LocustAChatter_BurnOminid01Cue',Addressee=GUDRole_Recipient)
	GUDLines(149)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKilledEnemyWithFlamethrower.LocustAChatter_BurnOoman01Cue',Addressee=GUDRole_Recipient)
	GUDLines(150)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAKilledEnemyWithFlamethrower.LocustAChatter_EatFire01Cue',Addressee=GUDRole_Recipient)
	GUDActions(GUDAction_KilledEnemyFlamethrower_I)=(LineIndices=(147,148,149,150))

	GUDLines(151)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAGatlingGunOverheats.LocustAChatter_Hot01Cue',bAlwaysLoad=1)
	GUDLines(152)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAGatlingGunOverheats.LocustAChatter_TooHot02Cue')
	GUDActions(GUDAction_GatlingOverheated_I)=(LineIndices=(151,152))

	GUDLines(153)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemiesSpotted.LocustAChatter_Incoming_Scream02Cue',bAlwaysLoad=1)
	GUDLines(154)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAEnemiesSpotted.LocustAChatter_Incoming_Scream01Cue')
	GUDActions(GUDAction_MortarLaunched_EW)=(LineIndices=(153,154))

	GUDLines(155)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAThrowingGrenades.LocustAChatter_Ink01Cue',bAlwaysLoad=1)
	GUDLines(156)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAThrowingGrenades.LocustAChatter_Ink02Cue')
	GUDLines(157)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAThrowingGrenades.LocustAChatter_InkOut01Cue')
	GUDLines(158)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAThrowingGrenades.LocustAChatter_InkOut02Cue')
	GUDActions(GUDAction_ThrowingInkGrenade_I)=(LineIndices=(155,156,157,158))

	GUDLines(159)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAThrowingGrenades.LocustAChatter_ComingInk01Cue',bAlwaysLoad=1)
	GUDLines(160)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAThrowingGrenades.LocustAChatter_ComingInk02Cue')
	GUDActions(GUDAction_ThrowingInkGrenade_EW)=(LineIndices=(159,160))

	GUDLines(161)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingWoundedAsMeatshield.LocustAChatter_OomanChunk02Cue',bAlwaysLoad=1)
	GUDLines(162)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneATakingWoundedAsMeatshield.LocustAChatter_OomanChunk01Cue')
	GUDActions(GUDAction_StuckExplosiveToEnemy_I)=(LineIndices=(161,162))

	GUDLines(163)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAShortCommentBeforeBlowingUp.LocustAChatter_FrustratedGrunt03Cue',bAlwaysLoad=1)
	GUDLines(164)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAShortCommentBeforeBlowingUp.LocustAChatter_FrustratedGrunt04Cue')
	GUDLines(165)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAShortCommentBeforeBlowingUp.LocustAChatter_No01Cue')
	GUDLines(166)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAShortCommentBeforeBlowingUp.LocustAChatter_No02Cue')
	GUDLines(167)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAShortCommentBeforeBlowingUp.LocustAChatter_No03Cue')
	GUDActions(GUDAction_StuckExplosiveToEnemy_R)=(LineIndices=(163,164,165,166,167))

	GUDLines(168)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAAttachingGrenadeToWall.LocustAChatter_Armed01Cue',bAlwaysLoad=1)
	GUDLines(169)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAAttachingGrenadeToWall.LocustAChatter_Armed02Cue')
	GUDLines(170)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAAttachingGrenadeToWall.LocustAChatter_Set01Cue')
	GUDLines(171)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAAttachingGrenadeToWall.LocustAChatter_Set02Cue')
	GUDActions(GUDAction_GrenadeTrapSet_I)=(LineIndices=(168,169,170,171))

	GUDLines(172)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAPickedUpFlamethrower.LocustAChatter_Fire03Cue',bAlwaysLoad=1)
	GUDLines(173)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAPickedUpFlamethrower.LocustAChatter_Burn01Cue')
	GUDLines(174)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAPickedUpFlamethrower.LocustAChatter_Fire04Cue')
	GUDLines(175)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAPickedUpFlamethrower.LocustAChatter_Burn02Cue')
	GUDActions(GUDAction_PickedUpFlamethrower_I)=(LineIndices=(172,173,174,175))

	GUDLines(176)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAExecutingMeatshield.LocustAChatter_UselessMeat01Cue',bAlwaysLoad=1,Addressee=GUDRole_Recipient)
	GUDLines(177)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAExecutingMeatshield.LocustAChatter_WorthlessMeat01Cue',Addressee=GUDRole_Recipient)
	GUDLines(178)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAExecutingMeatshield.LocustAChatter_EmptyMeat01Cue',Addressee=GUDRole_Recipient)
	GUDLines(179)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAExecutingMeatshield.LocustAChatter_EmptyMeat02Cue',Addressee=GUDRole_Recipient)
	GUDLines(180)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAExecutingMeatshield.LocustAChatter_WorthlessMeat02Cue',Addressee=GUDRole_Recipient)
	GUDActions(GUDAction_ExecutedMeatShield_I)=(LineIndices=(176,177,178,179,180))

	GUDLines(181)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAWatchingWoundedCrawlAway.LocustAChatter_GrovelMeat02Cue',bAlwaysLoad=1,Addressee=GUDRole_Instigator)
	GUDLines(182)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAWatchingWoundedCrawlAway.LocustAChatter_GrovelMeat01Cue',Addressee=GUDRole_Instigator)
	GUDLines(183)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAWatchingWoundedCrawlAway.LocustAChatter_CrawlMeat02Cue',Addressee=GUDRole_Instigator)
	GUDLines(184)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAWatchingWoundedCrawlAway.LocustAChatter_CrawlMeat01Cue',Addressee=GUDRole_Instigator)
	GUDLines(185)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAWatchingWoundedCrawlAway.LocustAChatter_CrawlOoman02Cue',Addressee=GUDRole_Instigator)
	GUDLines(186)=(Audio=SoundCue'Locust_Drone_Chatter_Cue.DroneAWatchingWoundedCrawlAway.LocustAChatter_CrawlOoman01Cue',Addressee=GUDRole_Instigator)
	GUDActions(GUDAction_DBNOPawnCrawlingAway_EW)=(LineIndices=(181,182,183,184,185,186))

}
